$axure.loadCurrentPage({
  "url":"opprett_bruker.html",
  "generationDate":new Date(1400834543097.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ca8b69bf2d3b41c8a658388f428dfb56",
    "type":"Axure:Page",
    "name":"opprett bruker",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b66713c9cb746faaea7152a3f199e3b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2b40fb19f33c450284c7533e94ceefb7"},
{
          "id":"5ddb37003fbd4622b3080b079976d9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":150},
            "size":{
              "width":580,
              "height":540},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22209f2983394fe0a1ac365e72dcab40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":150},
                "size":{
                  "width":580,
                  "height":540},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u3.png"}},
{
          "id":"8b1c9cc57d4948ce85e084b1a9e31521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":120,
              "y":150},
            "size":{
              "width":490,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169bee24748c4e5eb8343ae57d6ce259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":120,
                  "y":150},
                "size":{
                  "width":490,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tilgang_login_-_responsive_view/u5.png"}},
{
          "id":"db3c968df9b9485e87b4bb0480dcde3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":185,
              "y":260},
            "size":{
              "width":365,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3cd2c0ef1e548a4b95145ca4c666e15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":185,
                  "y":260},
                "size":{
                  "width":365,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u7.png"}},
{
          "id":"ce841c68e270422fbe05b834ba782bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":185,
              "y":627},
            "size":{
              "width":365,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8325cc45365d44979604392a79c124d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":185,
                  "y":627},
                "size":{
                  "width":365,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u9.png"}},
{
          "id":"979dfbbe5cef4883b61f433fb81f9536",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":186,
              "y":241},
            "size":{
              "width":239,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b13397d8283d4af0beb05ec07c562d57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":186,
                  "y":241},
                "size":{
                  "width":239,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"087b3967c0404913a62fc8d11ba7f23b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":185,
              "y":339},
            "size":{
              "width":365,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"862aba929ca34bff8b9d5f071011f626",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":185,
                  "y":339},
                "size":{
                  "width":365,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u7.png"}},
{
          "id":"79881308ca534806a631a3f0f30b179a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":186,
              "y":320},
            "size":{
              "width":239,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a4c7094831e408baa5e1ae7bd7648c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":186,
                  "y":320},
                "size":{
                  "width":239,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"954c0c7f24f2416aa021dd97d22d2ed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":185,
              "y":419},
            "size":{
              "width":365,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09dc779c5bb74aa1a139915f7a55e1db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":185,
                  "y":419},
                "size":{
                  "width":365,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u7.png"}},
{
          "id":"64da8295c22a48e0a7111fa8aa3265b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":186,
              "y":400},
            "size":{
              "width":239,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b568bafc39e14399b719a10febd36b6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":186,
                  "y":400},
                "size":{
                  "width":239,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faacc81019de4138bcbe306ca7639459",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":185,
              "y":567},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67b1453fd6b49518c472220275fa18a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":185,
                  "y":567},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u21.png"}},
{
          "id":"4febbe64660f4418b184f725ae5fada6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":212,
              "y":569},
            "size":{
              "width":338,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16c08e12bf0c4fd1be8588781a4e39e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":212,
                  "y":569},
                "size":{
                  "width":338,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c8c5e852926411fbbfaa26157a9f078",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":185,
              "y":500},
            "size":{
              "width":85,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95960960e322408ca584f76d140cb96b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":185,
                  "y":500},
                "size":{
                  "width":85,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u25.png"}},
{
          "id":"bd347b42e4954016ada65e35ede599d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":186,
              "y":481},
            "size":{
              "width":239,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22cdf14672a04077a4eb05566b19d69e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":186,
                  "y":481},
                "size":{
                  "width":239,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac71bb0fe4f0451c841e187333d4a842",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":243,
              "y":517},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f5a35c8f3d0460b804f8e96540bfe59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":243,
                  "y":517},
                "size":{
                  "width":20,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u29.png"}},
{
          "id":"0ce0a7cfe66f4822b2117be0bf0c7f7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":280,
              "y":500},
            "size":{
              "width":105,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24015ffb708b4acfbeedfaad434e1251",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":280,
                  "y":500},
                "size":{
                  "width":105,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u31.png"}},
{
          "id":"7649a8b0c0d241978acd9b52c56a8752",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":355,
              "y":517},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3784550ba9b947c89c8be0dd2faa8bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":355,
                  "y":517},
                "size":{
                  "width":20,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u29.png"}},
{
          "id":"9d97f27ea7ff41959e36a128e3a5b6a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":395,
              "y":500},
            "size":{
              "width":75,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ce2a053af264f1ea2377fe54652d804",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":395,
                  "y":500},
                "size":{
                  "width":75,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u35.png"}},
{
          "id":"6c50c3f13a794d35bc01cf3f6d52a5c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":440,
              "y":517},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4223f4ab906d45f1be92febb0c5c0466",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":440,
                  "y":517},
                "size":{
                  "width":20,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u29.png"}},
{
          "id":"9206bc421ca442d5bbbf31353eb65060",
          "label":"brukervilkår",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":71,
              "y":688},
            "size":{
              "width":600,
              "height":670},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c39bc917f9624237a5aeb4556451ecee",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3f0a282dbebe4f60b706b5fb8b459596",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":-20},
                    "size":{
                      "width":580,
                      "height":680},
                    "borderWidth":"-1",
                    "outerShadow":{
                      "on":true,
                      "offsetX":0,
                      "offsetY":1,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.34901961684227}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b3a487c396242f186e550a785a6cb5b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":-20},
                        "size":{
                          "width":580,
                          "height":680},
                        "borderWidth":"-1",
                        "outerShadow":{
                          "on":true,
                          "offsetX":0,
                          "offsetY":1,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.34901961684227}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/opprett_bruker/u40.png"}},
{
                  "id":"fc5da85843a84646ab96225ff4215543",
                  "label":"brukervilkår heading",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                    "fontSize":"34px",
                    "fontWeight":"900",
                    "location":{
                      "x":55,
                      "y":0},
                    "size":{
                      "width":490,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa62767c5f254e2db3195b2ef44e72bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                        "fontSize":"34px",
                        "fontWeight":"900",
                        "location":{
                          "x":55,
                          "y":0},
                        "size":{
                          "width":490,
                          "height":60},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tilgang_login_-_responsive_view/u5.png"}},
{
                  "id":"10623ac807a1495ab9ff7a8f0fdb1ac9",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":30,
                      "y":110},
                    "size":{
                      "width":540,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"221455c624f045f9af6b2cc62a297367",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":30,
                          "y":110},
                        "size":{
                          "width":540,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3eaf60182e9e4ce1a78de09f8b45780a",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                    "fontSize":"19px",
                    "fontWeight":"900",
                    "location":{
                      "x":30,
                      "y":80},
                    "size":{
                      "width":540,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24c29d4afa05457ab94ae9dd15be1ef0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                        "fontSize":"19px",
                        "fontWeight":"900",
                        "location":{
                          "x":30,
                          "y":80},
                        "size":{
                          "width":540,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ea8f15ba4f56464689e5d678a31a526c",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":30,
                      "y":260},
                    "size":{
                      "width":540,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0eb5265a6524727ad48875e8683246f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":30,
                          "y":260},
                        "size":{
                          "width":540,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0a2e29c8c6d445d9b13b11e3a58f927f",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                    "fontSize":"19px",
                    "fontWeight":"900",
                    "location":{
                      "x":30,
                      "y":230},
                    "size":{
                      "width":540,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e58fddbf6da44aa7b5941964ec06c7b8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                        "fontSize":"19px",
                        "fontWeight":"900",
                        "location":{
                          "x":30,
                          "y":230},
                        "size":{
                          "width":540,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8dafd6a281e44f3eb8af81f547ccd14b",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":30,
                      "y":405},
                    "size":{
                      "width":540,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfa7a09054044834a67926d0e40504f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":30,
                          "y":405},
                        "size":{
                          "width":540,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dfa7c5f418844ef3a1966fcf66c4c65b",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                    "fontSize":"19px",
                    "fontWeight":"900",
                    "location":{
                      "x":30,
                      "y":375},
                    "size":{
                      "width":540,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c40a7a86f34d4fcaae2b3f2ac37662c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                        "fontSize":"19px",
                        "fontWeight":"900",
                        "location":{
                          "x":30,
                          "y":375},
                        "size":{
                          "width":540,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"50c4a6e65ac4427bbb9692c9f3f731d9",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":30,
                      "y":550},
                    "size":{
                      "width":540,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6936af90bfd54b87a6680cdac37f3c83",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":30,
                          "y":550},
                        "size":{
                          "width":540,
                          "height":85}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"97652db0f3f841a289ff32d8f1f7512f",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                    "fontSize":"19px",
                    "fontWeight":"900",
                    "location":{
                      "x":30,
                      "y":520},
                    "size":{
                      "width":540,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a7609572006143eeb2de8d6f9138dd2c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                        "fontSize":"19px",
                        "fontWeight":"900",
                        "location":{
                          "x":30,
                          "y":520},
                        "size":{
                          "width":540,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"81e2bee9d7af4c5ea04b4a7b84c7248d",
                  "label":"",
                  "parentDynamicPanel":"9206bc421ca442d5bbbf31353eb65060",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":-4},
                    "size":{
                      "width":540,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEEEEEE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/opprett_bruker/u60_line.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"cdbc509af880489697d7297dc3da0629",
          "label":"trig «brukervilkår»",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":564},
            "size":{
              "width":112,
              "height":26}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle brukervilkår slide down 500 ms",
                      "objectsToFades":[{
                          "objectPath":["9206bc421ca442d5bbbf31353eb65060"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"6ee3ae871e3947278df75c7ebb68396a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":700,
              "y":615},
            "size":{
              "width":300,
              "height":299}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdc5966bb7884affb30db0c8a50b8300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":615},
                "size":{
                  "width":300,
                  "height":299}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2b40fb19f33c450284c7533e94ceefb7":{
      "packageId":"2b40fb19f33c450284c7533e94ceefb7",
      "type":"Axure:Master",
      "name":"newspaper-header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f116adf1346348c589d6534e6e84206f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":753,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16de1730a3c245c88590db8c75a43f16",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":753,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/tilgang_login_-_responsive_view/u1.jpg"}}]}}},
  "objectPaths":{
    "3b66713c9cb746faaea7152a3f199e3b":{
      "scriptId":"u0",
      "f116adf1346348c589d6534e6e84206f":{
        "scriptId":"u1"},
      "16de1730a3c245c88590db8c75a43f16":{
        "scriptId":"u2"}},
    "5ddb37003fbd4622b3080b079976d9d0":{
      "scriptId":"u3"},
    "22209f2983394fe0a1ac365e72dcab40":{
      "scriptId":"u4"},
    "8b1c9cc57d4948ce85e084b1a9e31521":{
      "scriptId":"u5"},
    "169bee24748c4e5eb8343ae57d6ce259":{
      "scriptId":"u6"},
    "db3c968df9b9485e87b4bb0480dcde3c":{
      "scriptId":"u7"},
    "d3cd2c0ef1e548a4b95145ca4c666e15":{
      "scriptId":"u8"},
    "ce841c68e270422fbe05b834ba782bd4":{
      "scriptId":"u9"},
    "8325cc45365d44979604392a79c124d2":{
      "scriptId":"u10"},
    "979dfbbe5cef4883b61f433fb81f9536":{
      "scriptId":"u11"},
    "b13397d8283d4af0beb05ec07c562d57":{
      "scriptId":"u12"},
    "087b3967c0404913a62fc8d11ba7f23b":{
      "scriptId":"u13"},
    "862aba929ca34bff8b9d5f071011f626":{
      "scriptId":"u14"},
    "79881308ca534806a631a3f0f30b179a":{
      "scriptId":"u15"},
    "3a4c7094831e408baa5e1ae7bd7648c8":{
      "scriptId":"u16"},
    "954c0c7f24f2416aa021dd97d22d2ed8":{
      "scriptId":"u17"},
    "09dc779c5bb74aa1a139915f7a55e1db":{
      "scriptId":"u18"},
    "64da8295c22a48e0a7111fa8aa3265b7":{
      "scriptId":"u19"},
    "b568bafc39e14399b719a10febd36b6c":{
      "scriptId":"u20"},
    "faacc81019de4138bcbe306ca7639459":{
      "scriptId":"u21"},
    "e67b1453fd6b49518c472220275fa18a":{
      "scriptId":"u22"},
    "4febbe64660f4418b184f725ae5fada6":{
      "scriptId":"u23"},
    "16c08e12bf0c4fd1be8588781a4e39e6":{
      "scriptId":"u24"},
    "6c8c5e852926411fbbfaa26157a9f078":{
      "scriptId":"u25"},
    "95960960e322408ca584f76d140cb96b":{
      "scriptId":"u26"},
    "bd347b42e4954016ada65e35ede599d3":{
      "scriptId":"u27"},
    "22cdf14672a04077a4eb05566b19d69e":{
      "scriptId":"u28"},
    "ac71bb0fe4f0451c841e187333d4a842":{
      "scriptId":"u29"},
    "1f5a35c8f3d0460b804f8e96540bfe59":{
      "scriptId":"u30"},
    "0ce0a7cfe66f4822b2117be0bf0c7f7e":{
      "scriptId":"u31"},
    "24015ffb708b4acfbeedfaad434e1251":{
      "scriptId":"u32"},
    "7649a8b0c0d241978acd9b52c56a8752":{
      "scriptId":"u33"},
    "3784550ba9b947c89c8be0dd2faa8bf6":{
      "scriptId":"u34"},
    "9d97f27ea7ff41959e36a128e3a5b6a1":{
      "scriptId":"u35"},
    "5ce2a053af264f1ea2377fe54652d804":{
      "scriptId":"u36"},
    "6c50c3f13a794d35bc01cf3f6d52a5c3":{
      "scriptId":"u37"},
    "4223f4ab906d45f1be92febb0c5c0466":{
      "scriptId":"u38"},
    "9206bc421ca442d5bbbf31353eb65060":{
      "scriptId":"u39"},
    "3f0a282dbebe4f60b706b5fb8b459596":{
      "scriptId":"u40"},
    "5b3a487c396242f186e550a785a6cb5b":{
      "scriptId":"u41"},
    "fc5da85843a84646ab96225ff4215543":{
      "scriptId":"u42"},
    "fa62767c5f254e2db3195b2ef44e72bc":{
      "scriptId":"u43"},
    "10623ac807a1495ab9ff7a8f0fdb1ac9":{
      "scriptId":"u44"},
    "221455c624f045f9af6b2cc62a297367":{
      "scriptId":"u45"},
    "3eaf60182e9e4ce1a78de09f8b45780a":{
      "scriptId":"u46"},
    "24c29d4afa05457ab94ae9dd15be1ef0":{
      "scriptId":"u47"},
    "ea8f15ba4f56464689e5d678a31a526c":{
      "scriptId":"u48"},
    "c0eb5265a6524727ad48875e8683246f":{
      "scriptId":"u49"},
    "0a2e29c8c6d445d9b13b11e3a58f927f":{
      "scriptId":"u50"},
    "e58fddbf6da44aa7b5941964ec06c7b8":{
      "scriptId":"u51"},
    "8dafd6a281e44f3eb8af81f547ccd14b":{
      "scriptId":"u52"},
    "bfa7a09054044834a67926d0e40504f4":{
      "scriptId":"u53"},
    "dfa7c5f418844ef3a1966fcf66c4c65b":{
      "scriptId":"u54"},
    "c40a7a86f34d4fcaae2b3f2ac37662c6":{
      "scriptId":"u55"},
    "50c4a6e65ac4427bbb9692c9f3f731d9":{
      "scriptId":"u56"},
    "6936af90bfd54b87a6680cdac37f3c83":{
      "scriptId":"u57"},
    "97652db0f3f841a289ff32d8f1f7512f":{
      "scriptId":"u58"},
    "a7609572006143eeb2de8d6f9138dd2c":{
      "scriptId":"u59"},
    "81e2bee9d7af4c5ea04b4a7b84c7248d":{
      "scriptId":"u60"},
    "cdbc509af880489697d7297dc3da0629":{
      "scriptId":"u61"},
    "6ee3ae871e3947278df75c7ebb68396a":{
      "scriptId":"u62"},
    "fdc5966bb7884affb30db0c8a50b8300":{
      "scriptId":"u63"}}});