$axure.loadCurrentPage({
  "url":"feilkort__enkel_registrering_for_andre_gang.html",
  "generationDate":new Date(1398412541751.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6aeb64faf5e9406ebab0d1f7f85c183e",
    "type":"Axure:Page",
    "name":"feilkort: enkel registrering for ANDRE gang",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a7963cd3dd4545afbf28677ae6e24848",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":274},
            "size":{
              "width":2760,
              "height":1426},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88d3a8c7bf554095b3f51f2198abd6ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":274},
                "size":{
                  "width":2760,
                  "height":1426},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/feilkort__enkel_registrering_for_andre_gang/u0.png"}},
{
          "id":"3b66713c9cb746faaea7152a3f199e3b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2b40fb19f33c450284c7533e94ceefb7"},
{
          "id":"5ddb37003fbd4622b3080b079976d9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":150},
            "size":{
              "width":580,
              "height":210},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22209f2983394fe0a1ac365e72dcab40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":150},
                "size":{
                  "width":580,
                  "height":210},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/feilkort__familiel_p_for_andre_gang/u3.png"}},
{
          "id":"8b1c9cc57d4948ce85e084b1a9e31521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontSize":"34px",
            "fontWeight":"900",
            "location":{
              "x":120,
              "y":150},
            "size":{
              "width":490,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169bee24748c4e5eb8343ae57d6ce259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontSize":"34px",
                "fontWeight":"900",
                "location":{
                  "x":120,
                  "y":150},
                "size":{
                  "width":490,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u19.png"}},
{
          "id":"ce841c68e270422fbe05b834ba782bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":332,
              "y":301},
            "size":{
              "width":68,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8325cc45365d44979604392a79c124d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":332,
                  "y":301},
                "size":{
                  "width":68,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bruker_opprettet/u7.png"}},
{
          "id":"f130437c30834808947858274e0805a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "paddingTop":"20",
            "paddingBottom":"20",
            "location":{
              "x":100,
              "y":220},
            "size":{
              "width":540,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d87f14f85844a97aa25ab0cfdac2fa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "paddingTop":"20",
                "paddingBottom":"20",
                "location":{
                  "x":100,
                  "y":220},
                "size":{
                  "width":540,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ef7f837404c42769e8afa7de8e47111",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":630,
              "y":850},
            "size":{
              "width":380,
              "height":380},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3027a49b6b764082a12512f2c58d33d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":630,
                  "y":850},
                "size":{
                  "width":380,
                  "height":380},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/feilkort__systemfeil/u13.png"}},
{
          "id":"3f6cb467a9a346e1a57ba49251ec23ab",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":284},
            "size":{
              "width":10,
              "height":635},
            "rotation":"324",
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC00}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/feilkort__enkel_registrering_for_andre_gang/u15_line.png"}},
{
          "id":"b8e28faf84b941b89656f020846d13e2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":225.666900634766,
              "y":452.301818847656},
            "size":{
              "width":10,
              "height":635},
            "rotation":"324",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/feilkort__enkel_registrering_for_andre_gang/u16_line.png"}},
{
          "id":"fe03c1653ff24244a5635bafd5cccb92",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":462},
            "size":{
              "width":10,
              "height":635},
            "rotation":"216",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/feilkort__enkel_registrering_for_andre_gang/u16_line.png"}},
{
          "id":"8cbf988a188340e0803a0462299a69ab",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":1042.3017578125},
            "size":{
              "width":10,
              "height":635},
            "rotation":"324",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/feilkort__enkel_registrering_for_andre_gang/u16_line.png"}},
{
          "id":"3fe983c218d5431bbb4160736ac62701",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":1052.3017578125},
            "size":{
              "width":10,
              "height":635},
            "rotation":"216",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/feilkort__enkel_registrering_for_andre_gang/u16_line.png"}},
{
          "id":"44a5ea8c43f94656a385ee845e5e5243",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "paddingTop":"20",
            "paddingBottom":"20",
            "location":{
              "x":40,
              "y":450},
            "size":{
              "width":540,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e9eca9301554c83af27d68fb2eefc1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "paddingTop":"20",
                "paddingBottom":"20",
                "location":{
                  "x":40,
                  "y":450},
                "size":{
                  "width":540,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2b40fb19f33c450284c7533e94ceefb7":{
      "packageId":"2b40fb19f33c450284c7533e94ceefb7",
      "type":"Axure:Master",
      "name":"newspaper-header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f116adf1346348c589d6534e6e84206f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":753,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16de1730a3c245c88590db8c75a43f16",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":753,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/tilgang_login/u1.jpg"}}]}}},
  "objectPaths":{
    "a7963cd3dd4545afbf28677ae6e24848":{
      "scriptId":"u0"},
    "88d3a8c7bf554095b3f51f2198abd6ce":{
      "scriptId":"u1"},
    "3b66713c9cb746faaea7152a3f199e3b":{
      "scriptId":"u2",
      "f116adf1346348c589d6534e6e84206f":{
        "scriptId":"u3"},
      "16de1730a3c245c88590db8c75a43f16":{
        "scriptId":"u4"}},
    "5ddb37003fbd4622b3080b079976d9d0":{
      "scriptId":"u5"},
    "22209f2983394fe0a1ac365e72dcab40":{
      "scriptId":"u6"},
    "8b1c9cc57d4948ce85e084b1a9e31521":{
      "scriptId":"u7"},
    "169bee24748c4e5eb8343ae57d6ce259":{
      "scriptId":"u8"},
    "ce841c68e270422fbe05b834ba782bd4":{
      "scriptId":"u9"},
    "8325cc45365d44979604392a79c124d2":{
      "scriptId":"u10"},
    "f130437c30834808947858274e0805a1":{
      "scriptId":"u11"},
    "9d87f14f85844a97aa25ab0cfdac2fa7":{
      "scriptId":"u12"},
    "7ef7f837404c42769e8afa7de8e47111":{
      "scriptId":"u13"},
    "3027a49b6b764082a12512f2c58d33d7":{
      "scriptId":"u14"},
    "3f6cb467a9a346e1a57ba49251ec23ab":{
      "scriptId":"u15"},
    "b8e28faf84b941b89656f020846d13e2":{
      "scriptId":"u16"},
    "fe03c1653ff24244a5635bafd5cccb92":{
      "scriptId":"u17"},
    "8cbf988a188340e0803a0462299a69ab":{
      "scriptId":"u18"},
    "3fe983c218d5431bbb4160736ac62701":{
      "scriptId":"u19"},
    "44a5ea8c43f94656a385ee845e5e5243":{
      "scriptId":"u20"},
    "2e9eca9301554c83af27d68fb2eefc1c":{
      "scriptId":"u21"}}});