$axure.loadCurrentPage({
  "url":"engangskj_psiden_1.html",
  "generationDate":new Date(1398346611326.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1e2437fe50df477cbaefb7681f2ce703",
    "type":"Axure:Page",
    "name":"engangskjøpsiden",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b66713c9cb746faaea7152a3f199e3b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2b40fb19f33c450284c7533e94ceefb7"},
{
          "id":"5ddb37003fbd4622b3080b079976d9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":150},
            "size":{
              "width":580,
              "height":260},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22209f2983394fe0a1ac365e72dcab40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":150},
                "size":{
                  "width":580,
                  "height":260},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/engangskj_psiden/u3.png"}},
{
          "id":"8b1c9cc57d4948ce85e084b1a9e31521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontSize":"34px",
            "fontWeight":"900",
            "location":{
              "x":120,
              "y":150},
            "size":{
              "width":490,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169bee24748c4e5eb8343ae57d6ce259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontSize":"34px",
                "fontWeight":"900",
                "location":{
                  "x":120,
                  "y":150},
                "size":{
                  "width":490,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u19.png"}},
{
          "id":"ce841c68e270422fbe05b834ba782bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":290,
              "y":280},
            "size":{
              "width":150,
              "height":100},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8325cc45365d44979604392a79c124d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":290,
                  "y":280},
                "size":{
                  "width":150,
                  "height":100},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/engangskj_psiden/u7.png"}},
{
          "id":"c512aaf2c7674daf9029f8ec3ed9c489",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "paddingTop":"20",
            "paddingBottom":"20",
            "location":{
              "x":100,
              "y":210},
            "size":{
              "width":540,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e24ae10884a48d19297211bec8059b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "paddingTop":"20",
                "paddingBottom":"20",
                "location":{
                  "x":100,
                  "y":210},
                "size":{
                  "width":540,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"078b5e3b915044bf94c1c298fefa22ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":300,
              "y":297},
            "size":{
              "width":130,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c862e71fbff4e4eb0a62c7ca11026a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":300,
                  "y":297},
                "size":{
                  "width":130,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e6e923d71bc4ab7a4eaa5f1036bb828",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"24px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":300,
              "y":330},
            "size":{
              "width":130,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc8b8edfd7034c6abaf3231d29b47acc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"24px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":300,
                  "y":330},
                "size":{
                  "width":130,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d35fd1a309645069a6d7fd12f1c86c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":120,
              "y":280},
            "size":{
              "width":150,
              "height":100},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6cc7ef85eec47a48e2e16a9b896c284",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":120,
                  "y":280},
                "size":{
                  "width":150,
                  "height":100},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/engangskj_psiden/u7.png"}},
{
          "id":"44bf16286ebd4b1e9faede599468546a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":130,
              "y":297},
            "size":{
              "width":130,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31a0785aac28438aa51961876977dc36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":130,
                  "y":297},
                "size":{
                  "width":130,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a42d9fd5c64543979f60569040c9886b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"24px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":130,
              "y":330},
            "size":{
              "width":130,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41f3ef6caa474742a37ff5013dc71986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"24px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":130,
                  "y":330},
                "size":{
                  "width":130,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8ea21a012d744c097ff07b019302cc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":460,
              "y":280},
            "size":{
              "width":150,
              "height":100},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b1070993ba1443b91f6ac9ce262d0f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":460,
                  "y":280},
                "size":{
                  "width":150,
                  "height":100},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/engangskj_psiden/u7.png"}},
{
          "id":"98141f13fb2f4ffb837a0bfe6171d4ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":470,
              "y":297},
            "size":{
              "width":130,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"992445e26e25496191b447fe5b58ae08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":470,
                  "y":297},
                "size":{
                  "width":130,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae0983e692ab409cae4adf55bd11a225",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"24px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":470,
              "y":330},
            "size":{
              "width":130,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"874fe125c0234cd2837aaea9f9fb38ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"24px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":470,
                  "y":330},
                "size":{
                  "width":130,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d942a93c4bb547e5918303db1fa3a3f8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":270},
            "size":{
              "width":170,
              "height":120}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open tast kjøpskode in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"tast_kj_pskode_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "2b40fb19f33c450284c7533e94ceefb7":{
      "packageId":"2b40fb19f33c450284c7533e94ceefb7",
      "type":"Axure:Master",
      "name":"newspaper-header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f116adf1346348c589d6534e6e84206f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":753,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16de1730a3c245c88590db8c75a43f16",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":753,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/tilgang_login/u1.jpg"}}]}}},
  "objectPaths":{
    "3b66713c9cb746faaea7152a3f199e3b":{
      "scriptId":"u0",
      "f116adf1346348c589d6534e6e84206f":{
        "scriptId":"u1"},
      "16de1730a3c245c88590db8c75a43f16":{
        "scriptId":"u2"}},
    "5ddb37003fbd4622b3080b079976d9d0":{
      "scriptId":"u3"},
    "22209f2983394fe0a1ac365e72dcab40":{
      "scriptId":"u4"},
    "8b1c9cc57d4948ce85e084b1a9e31521":{
      "scriptId":"u5"},
    "169bee24748c4e5eb8343ae57d6ce259":{
      "scriptId":"u6"},
    "ce841c68e270422fbe05b834ba782bd4":{
      "scriptId":"u7"},
    "8325cc45365d44979604392a79c124d2":{
      "scriptId":"u8"},
    "c512aaf2c7674daf9029f8ec3ed9c489":{
      "scriptId":"u9"},
    "9e24ae10884a48d19297211bec8059b2":{
      "scriptId":"u10"},
    "078b5e3b915044bf94c1c298fefa22ef":{
      "scriptId":"u11"},
    "7c862e71fbff4e4eb0a62c7ca11026a2":{
      "scriptId":"u12"},
    "7e6e923d71bc4ab7a4eaa5f1036bb828":{
      "scriptId":"u13"},
    "dc8b8edfd7034c6abaf3231d29b47acc":{
      "scriptId":"u14"},
    "4d35fd1a309645069a6d7fd12f1c86c2":{
      "scriptId":"u15"},
    "b6cc7ef85eec47a48e2e16a9b896c284":{
      "scriptId":"u16"},
    "44bf16286ebd4b1e9faede599468546a":{
      "scriptId":"u17"},
    "31a0785aac28438aa51961876977dc36":{
      "scriptId":"u18"},
    "a42d9fd5c64543979f60569040c9886b":{
      "scriptId":"u19"},
    "41f3ef6caa474742a37ff5013dc71986":{
      "scriptId":"u20"},
    "c8ea21a012d744c097ff07b019302cc8":{
      "scriptId":"u21"},
    "1b1070993ba1443b91f6ac9ce262d0f9":{
      "scriptId":"u22"},
    "98141f13fb2f4ffb837a0bfe6171d4ba":{
      "scriptId":"u23"},
    "992445e26e25496191b447fe5b58ae08":{
      "scriptId":"u24"},
    "ae0983e692ab409cae4adf55bd11a225":{
      "scriptId":"u25"},
    "874fe125c0234cd2837aaea9f9fb38ed":{
      "scriptId":"u26"},
    "d942a93c4bb547e5918303db1fa3a3f8":{
      "scriptId":"u27"}}});