$axure.loadCurrentPage({
  "url":"insentivside__uten_tidsbegrenset_-_responsive_view.html",
  "generationDate":new Date(1400834542517.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e12e96db62604fb687a0cf9f4edec726",
    "type":"Axure:Page",
    "name":"insentivside (UTEN tidsbegrenset - responsive view)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"afe9564566324d818afd3ed33c60eb6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontWeight":"900",
            "horizontalAlignment":"center",
            "location":{
              "x":0,
              "y":241},
            "size":{
              "width":740,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61533205a7f64b17add8f450c5f3c0b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontWeight":"900",
                "horizontalAlignment":"center",
                "location":{
                  "x":0,
                  "y":241},
                "size":{
                  "width":740,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e95cd1ca91a84b9a8a61440b2f707989",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":486},
            "size":{
              "width":750,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u2_line.png"}},
{
          "id":"6c9e540ab4fa4eddb3a4bc4797d33429",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":348,
              "y":581},
            "size":{
              "width":82,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c31625d7c13643de908a65c01c6e5ff9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":348,
                  "y":581},
                "size":{
                  "width":82,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u3.png"}},
{
          "id":"3355313db8644ab69e16e44d28fc669d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":589},
            "size":{
              "width":46,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9046215911d4b7caf8bfacc35bb5882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":589},
                "size":{
                  "width":46,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u5.jpg"}},
{
          "id":"6025bee208324262a3f6c60ab1758fe4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-2,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"43409402394842098b88ddcff669394e"},
{
          "id":"b42397ea3f90487380a605923d2513d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"16px",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":400},
            "size":{
              "width":580,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2c7f583e46646bfa8950f1b9ca95f79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"16px",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":80,
                  "y":400},
                "size":{
                  "width":580,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d331e76a898c43cca897d6f2d88e80d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "horizontalAlignment":"right",
            "location":{
              "x":-10,
              "y":331},
            "size":{
              "width":350,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"398a471fa79d4c91a3a62a5a30486847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "horizontalAlignment":"right",
                "location":{
                  "x":-10,
                  "y":331},
                "size":{
                  "width":350,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8ce23ec6ad14b778412ade31fc6498a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "location":{
              "x":400,
              "y":331},
            "size":{
              "width":350,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cde609d101f64655bca3fff930baeae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "location":{
                  "x":400,
                  "y":331},
                "size":{
                  "width":350,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"787bf394345e4eb3a9bb1e848aa78dfa",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":320},
            "size":{
              "width":10,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u16_line.png"}},
{
          "id":"0ab9054fffd44b0eb1bfd8a8260a0489",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontWeight":"900",
            "horizontalAlignment":"center",
            "location":{
              "x":0,
              "y":506},
            "size":{
              "width":740,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22dbc4c7b4dc42918337cf618ee806d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontWeight":"900",
                "horizontalAlignment":"center",
                "location":{
                  "x":0,
                  "y":506},
                "size":{
                  "width":740,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d0a7beb00ee46e9a1fe61919caeef09",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":646},
            "size":{
              "width":750,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u2_line.png"}},
{
          "id":"c74062b4046e4123afd71126cb400814",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontWeight":"900",
            "horizontalAlignment":"center",
            "location":{
              "x":0,
              "y":669},
            "size":{
              "width":740,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c1d8f2cd381418aaeb82b8da25c703e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontWeight":"900",
                "horizontalAlignment":"center",
                "location":{
                  "x":0,
                  "y":669},
                "size":{
                  "width":740,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1bea160496b4b63b3d435726033d58a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":828},
            "size":{
              "width":580,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d9dbac4cc134a059515f17ffeca6f67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":80,
                  "y":828},
                "size":{
                  "width":580,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac982d3b1e3b4566991d391189174a01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "horizontalAlignment":"right",
            "location":{
              "x":160,
              "y":759},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d98fb25e9984410da28fcaf62a89a61b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "horizontalAlignment":"right",
                "location":{
                  "x":160,
                  "y":759},
                "size":{
                  "width":180,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc49fbf86c7448ce93b45e8d52f5a1f4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":748},
            "size":{
              "width":10,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u16_line.png"}},
{
          "id":"f05d9b4e2d224c1b84704be7593b7626",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "location":{
              "x":400,
              "y":759},
            "size":{
              "width":181,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7a37f7b360842dcb5d101ef783b0df5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "location":{
                  "x":400,
                  "y":759},
                "size":{
                  "width":181,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc01c20466414ce1852e78b764f9590c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":901}},
          "adaptiveStyles":{
},
          "masterId":"b51107c95ed542ad8315389bac1b78b4"},
{
          "id":"d322c868b70d48f08c04dc8ca02c419a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"ab081a9be1374b3083257288fa2a8393"},
{
          "id":"393461fc7ac64ecb92f25b013d3267db",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontWeight":"900",
            "horizontalAlignment":"center",
            "lineSpacing":"34px",
            "location":{
              "x":910,
              "y":241},
            "size":{
              "width":480,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6161a40eab3045688ab03f438dcdeaee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontWeight":"900",
                "horizontalAlignment":"center",
                "lineSpacing":"34px",
                "location":{
                  "x":910,
                  "y":241},
                "size":{
                  "width":480,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70c869e98d8a44ffae8068f2bf167949",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"16px",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":910,
              "y":392},
            "size":{
              "width":480,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b041bbe6234c2e8a82a6eb5356820b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"16px",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":910,
                  "y":392},
                "size":{
                  "width":480,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19ae4804965345c9854ee7150aa705e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "horizontalAlignment":"center",
            "location":{
              "x":910,
              "y":300},
            "size":{
              "width":480,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36368615a16c4ba6bec3999753d1c42f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "horizontalAlignment":"center",
                "location":{
                  "x":910,
                  "y":300},
                "size":{
                  "width":480,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9d495d3cb8947ffafcd3590cc1d4108",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "horizontalAlignment":"center",
            "location":{
              "x":910,
              "y":336},
            "size":{
              "width":480,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df47666a92640fc87eccb3bea2a4bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "horizontalAlignment":"center",
                "location":{
                  "x":910,
                  "y":336},
                "size":{
                  "width":480,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34eb72b5732344e1a42cd69aacc3840d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":475},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u48_line.png"}},
{
          "id":"29578c8dbda94000a76d2b9657fef932",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontWeight":"900",
            "horizontalAlignment":"center",
            "location":{
              "x":910,
              "y":495},
            "size":{
              "width":480,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dfef65b9b4a4cdd9cb3c790abf0570e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontWeight":"900",
                "horizontalAlignment":"center",
                "location":{
                  "x":910,
                  "y":495},
                "size":{
                  "width":480,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8688af4a506a468a8d1754e2d79686fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":1128,
              "y":565},
            "size":{
              "width":82,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ca44628edb44cb7b273db1932bf78a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":1128,
                  "y":565},
                "size":{
                  "width":82,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u3.png"}},
{
          "id":"f8c13079e86545dd925d6ef689f9160f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":573},
            "size":{
              "width":46,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b29aa2258da04f98bb629e89ce1dbdb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1075,
                  "y":573},
                "size":{
                  "width":46,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u5.jpg"}},
{
          "id":"86730c71546b46fe810c0f277ce870e1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":630},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u48_line.png"}},
{
          "id":"e8792320f00b49a29276970be47ad2d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontWeight":"900",
            "horizontalAlignment":"center",
            "lineSpacing":"34px",
            "location":{
              "x":910,
              "y":657},
            "size":{
              "width":480,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9dd596b97564bd19ca3697f8493ebf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontWeight":"900",
                "horizontalAlignment":"center",
                "lineSpacing":"34px",
                "location":{
                  "x":910,
                  "y":657},
                "size":{
                  "width":480,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"061c6147fa494bb48ea4a22fcbbb8bbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "horizontalAlignment":"center",
            "location":{
              "x":910,
              "y":720},
            "size":{
              "width":480,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1bb60129af94ed6a5a8b5a527399bcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "horizontalAlignment":"center",
                "location":{
                  "x":910,
                  "y":720},
                "size":{
                  "width":480,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8add14570b3644fa907596ab2cfe1825",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "horizontalAlignment":"center",
            "location":{
              "x":910,
              "y":756},
            "size":{
              "width":480,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d8c3c299b634a8eaaaec32618f7fccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "horizontalAlignment":"center",
                "location":{
                  "x":910,
                  "y":756},
                "size":{
                  "width":480,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8942ba4724f148409aef26e11e65fcd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":910,
              "y":810},
            "size":{
              "width":480,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72b567259e6a481790a070dc4b28ab49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":910,
                  "y":810},
                "size":{
                  "width":480,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d161fd729d794af1ad804df6922939f5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":940}},
          "adaptiveStyles":{
},
          "masterId":"4391fc7d98bf4fd497f62a61664d58f4"}]}},
  "masters":{
    "43409402394842098b88ddcff669394e":{
      "packageId":"43409402394842098b88ddcff669394e",
      "type":"Axure:Master",
      "name":"card header fullbredde",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2f60ad64d85f456cb59b0920d4d8b5c3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":750,
                "height":201}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a10337325f140c5b7666d1f0f8c5753",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":750,
                    "height":201}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u8.jpg"}}]}},
    "b51107c95ed542ad8315389bac1b78b4":{
      "packageId":"b51107c95ed542ad8315389bac1b78b4",
      "type":"Axure:Master",
      "name":"footer fullbredde",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f48046b10275499682e285dad9297209",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":750,
                "height":70},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"724ba94edc4e427e8caff0ce8f73eb1b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":750,
                    "height":70},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u33.png",
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u67.png"}},
{
            "id":"55f22b18148542aba18a4f61d706663a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"19px",
              "fontWeight":"200",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":0,
                "y":22},
              "size":{
                "width":750,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dd6225c8eca54207ae5dbdfaadeab3f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"19px",
                  "fontWeight":"200",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":22},
                  "size":{
                    "width":750,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}}]}},
    "ab081a9be1374b3083257288fa2a8393":{
      "packageId":"ab081a9be1374b3083257288fa2a8393",
      "type":"Axure:Master",
      "name":"card header litenbredde",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"62f593f25bf747969b8a085012e78ab9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":500,
                "height":210}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"509dfc52462e4626998b72e8ebc7b39e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":500,
                    "height":210}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u38.jpg"}}]}},
    "4391fc7d98bf4fd497f62a61664d58f4":{
      "packageId":"4391fc7d98bf4fd497f62a61664d58f4",
      "type":"Axure:Master",
      "name":"footer litenbredde",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f48046b10275499682e285dad9297209",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":500,
                "height":120},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"724ba94edc4e427e8caff0ce8f73eb1b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":500,
                    "height":120},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u33.png",
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u67.png"}},
{
            "id":"55f22b18148542aba18a4f61d706663a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"19px",
              "fontWeight":"200",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":0,
                "y":30},
              "size":{
                "width":500,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dd6225c8eca54207ae5dbdfaadeab3f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"19px",
                  "fontWeight":"200",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":30},
                  "size":{
                    "width":500,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "afe9564566324d818afd3ed33c60eb6d":{
      "scriptId":"u0"},
    "61533205a7f64b17add8f450c5f3c0b9":{
      "scriptId":"u1"},
    "e95cd1ca91a84b9a8a61440b2f707989":{
      "scriptId":"u2"},
    "6c9e540ab4fa4eddb3a4bc4797d33429":{
      "scriptId":"u3"},
    "c31625d7c13643de908a65c01c6e5ff9":{
      "scriptId":"u4"},
    "3355313db8644ab69e16e44d28fc669d":{
      "scriptId":"u5"},
    "e9046215911d4b7caf8bfacc35bb5882":{
      "scriptId":"u6"},
    "6025bee208324262a3f6c60ab1758fe4":{
      "scriptId":"u7",
      "2f60ad64d85f456cb59b0920d4d8b5c3":{
        "scriptId":"u8"},
      "2a10337325f140c5b7666d1f0f8c5753":{
        "scriptId":"u9"}},
    "b42397ea3f90487380a605923d2513d0":{
      "scriptId":"u10"},
    "b2c7f583e46646bfa8950f1b9ca95f79":{
      "scriptId":"u11"},
    "d331e76a898c43cca897d6f2d88e80d6":{
      "scriptId":"u12"},
    "398a471fa79d4c91a3a62a5a30486847":{
      "scriptId":"u13"},
    "b8ce23ec6ad14b778412ade31fc6498a":{
      "scriptId":"u14"},
    "cde609d101f64655bca3fff930baeae0":{
      "scriptId":"u15"},
    "787bf394345e4eb3a9bb1e848aa78dfa":{
      "scriptId":"u16"},
    "0ab9054fffd44b0eb1bfd8a8260a0489":{
      "scriptId":"u17"},
    "22dbc4c7b4dc42918337cf618ee806d0":{
      "scriptId":"u18"},
    "9d0a7beb00ee46e9a1fe61919caeef09":{
      "scriptId":"u19"},
    "c74062b4046e4123afd71126cb400814":{
      "scriptId":"u20"},
    "4c1d8f2cd381418aaeb82b8da25c703e":{
      "scriptId":"u21"},
    "c1bea160496b4b63b3d435726033d58a":{
      "scriptId":"u22"},
    "9d9dbac4cc134a059515f17ffeca6f67":{
      "scriptId":"u23"},
    "ac982d3b1e3b4566991d391189174a01":{
      "scriptId":"u24"},
    "d98fb25e9984410da28fcaf62a89a61b":{
      "scriptId":"u25"},
    "cc49fbf86c7448ce93b45e8d52f5a1f4":{
      "scriptId":"u26"},
    "f05d9b4e2d224c1b84704be7593b7626":{
      "scriptId":"u27"},
    "d7a37f7b360842dcb5d101ef783b0df5":{
      "scriptId":"u28"},
    "bc01c20466414ce1852e78b764f9590c":{
      "scriptId":"u29",
      "f48046b10275499682e285dad9297209":{
        "scriptId":"u30"},
      "724ba94edc4e427e8caff0ce8f73eb1b":{
        "scriptId":"u31"},
      "55f22b18148542aba18a4f61d706663a":{
        "scriptId":"u32"},
      "dd6225c8eca54207ae5dbdfaadeab3f4":{
        "scriptId":"u33"}},
    "d322c868b70d48f08c04dc8ca02c419a":{
      "scriptId":"u34",
      "62f593f25bf747969b8a085012e78ab9":{
        "scriptId":"u35"},
      "509dfc52462e4626998b72e8ebc7b39e":{
        "scriptId":"u36"}},
    "393461fc7ac64ecb92f25b013d3267db":{
      "scriptId":"u37"},
    "6161a40eab3045688ab03f438dcdeaee":{
      "scriptId":"u38"},
    "70c869e98d8a44ffae8068f2bf167949":{
      "scriptId":"u39"},
    "20b041bbe6234c2e8a82a6eb5356820b":{
      "scriptId":"u40"},
    "19ae4804965345c9854ee7150aa705e8":{
      "scriptId":"u41"},
    "36368615a16c4ba6bec3999753d1c42f":{
      "scriptId":"u42"},
    "e9d495d3cb8947ffafcd3590cc1d4108":{
      "scriptId":"u43"},
    "7df47666a92640fc87eccb3bea2a4bed":{
      "scriptId":"u44"},
    "34eb72b5732344e1a42cd69aacc3840d":{
      "scriptId":"u45"},
    "29578c8dbda94000a76d2b9657fef932":{
      "scriptId":"u46"},
    "7dfef65b9b4a4cdd9cb3c790abf0570e":{
      "scriptId":"u47"},
    "8688af4a506a468a8d1754e2d79686fa":{
      "scriptId":"u48"},
    "7ca44628edb44cb7b273db1932bf78a3":{
      "scriptId":"u49"},
    "f8c13079e86545dd925d6ef689f9160f":{
      "scriptId":"u50"},
    "b29aa2258da04f98bb629e89ce1dbdb8":{
      "scriptId":"u51"},
    "86730c71546b46fe810c0f277ce870e1":{
      "scriptId":"u52"},
    "e8792320f00b49a29276970be47ad2d1":{
      "scriptId":"u53"},
    "f9dd596b97564bd19ca3697f8493ebf1":{
      "scriptId":"u54"},
    "061c6147fa494bb48ea4a22fcbbb8bbe":{
      "scriptId":"u55"},
    "b1bb60129af94ed6a5a8b5a527399bcd":{
      "scriptId":"u56"},
    "8add14570b3644fa907596ab2cfe1825":{
      "scriptId":"u57"},
    "3d8c3c299b634a8eaaaec32618f7fccc":{
      "scriptId":"u58"},
    "8942ba4724f148409aef26e11e65fcd2":{
      "scriptId":"u59"},
    "72b567259e6a481790a070dc4b28ab49":{
      "scriptId":"u60"},
    "d161fd729d794af1ad804df6922939f5":{
      "scriptId":"u61",
      "f48046b10275499682e285dad9297209":{
        "scriptId":"u62"},
      "724ba94edc4e427e8caff0ce8f73eb1b":{
        "scriptId":"u63"},
      "55f22b18148542aba18a4f61d706663a":{
        "scriptId":"u64"},
      "dd6225c8eca54207ae5dbdfaadeab3f4":{
        "scriptId":"u65"}}}});