$axure.loadCurrentPage({
  "url":"insentivside.html",
  "generationDate":new Date(1400832791290.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1c89d6744fc742778a20a6fb56ebd6cb",
    "type":"Axure:Page",
    "name":"insentivside",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fad38cd10ef74f2fb78d0da4f64dd769",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":560},
            "size":{
              "width":310,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open engangskjøpsiden in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"engangskj_psiden_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"572918e8cf61418aafbb62512051936e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"43409402394842098b88ddcff669394e"},
{
          "id":"bce628fd9a6e4630b2e55284d47121a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":460},
            "size":{
              "width":750,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u2_line.png"}},
{
          "id":"c99eb5dff48a4734925236da6a7ab6bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontWeight":"900",
            "horizontalAlignment":"center",
            "location":{
              "x":2,
              "y":483},
            "size":{
              "width":740,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94bbaeaa7e6947b29d20f227e617a345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontWeight":"900",
                "horizontalAlignment":"center",
                "location":{
                  "x":2,
                  "y":483},
                "size":{
                  "width":740,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5aef67c39a774d9e88a5c0a5223efc70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":82,
              "y":642},
            "size":{
              "width":580,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c06e6bdb25b54c8195e814630a776d52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":82,
                  "y":642},
                "size":{
                  "width":580,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15fe570ac197495ab2eebbb0c810cb71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "horizontalAlignment":"center",
            "location":{
              "x":13,
              "y":573},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed7dd2efed6e40daac80d4000bdcb96c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "horizontalAlignment":"center",
                "location":{
                  "x":13,
                  "y":573},
                "size":{
                  "width":180,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faa34d37bb1f4a29bd61c024033cf56c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "horizontalAlignment":"center",
            "location":{
              "x":224,
              "y":573},
            "size":{
              "width":295,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c26d62cefacf4f1881da6c245f3833b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "horizontalAlignment":"center",
                "location":{
                  "x":224,
                  "y":573},
                "size":{
                  "width":295,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a927b15d3844848bdeb300a0c5992ef",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":562},
            "size":{
              "width":10,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u16_line.png"}},
{
          "id":"990bfdd9325e4316b034f1164896c69a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
            "fontSize":"19px",
            "fontWeight":"200",
            "underline":true,
            "horizontalAlignment":"center",
            "location":{
              "x":552,
              "y":573},
            "size":{
              "width":181,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed0356309be640b2bdf2f0072781b133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                "fontSize":"19px",
                "fontWeight":"200",
                "underline":true,
                "horizontalAlignment":"center",
                "location":{
                  "x":552,
                  "y":573},
                "size":{
                  "width":181,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd19cad400754cb88a43c6d5ad823f77",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":531,
              "y":562},
            "size":{
              "width":10,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u16_line.png"}},
{
          "id":"20805ea394dc49d990aeb954252d1f9c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":715}},
          "adaptiveStyles":{
},
          "masterId":"b51107c95ed542ad8315389bac1b78b4"},
{
          "id":"83a933fa2e954fe09f5fa9e1a578cd66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontSize":"34px",
            "fontWeight":"900",
            "location":{
              "x":32,
              "y":220},
            "size":{
              "width":700,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"341e6126ebf844eaa72affdb544e9bd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontSize":"34px",
                "fontWeight":"900",
                "location":{
                  "x":32,
                  "y":220},
                "size":{
                  "width":700,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u22.png"}},
{
          "id":"3dc86850bf5b4b9c8ae07adf0ea8ed5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":286},
            "size":{
              "width":700,
              "height":150},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ffe7b8bb31041b4ba60dad9a4adf422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":286},
                "size":{
                  "width":700,
                  "height":150},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u24.png"}},
{
          "id":"b223da822b9540acb125b020a03f5132",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "lineSpacing":"20px",
            "location":{
              "x":22,
              "y":296},
            "size":{
              "width":710,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e135bd904e294a068fc72455c721de36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "lineSpacing":"20px",
                "location":{
                  "x":22,
                  "y":296},
                "size":{
                  "width":710,
                  "height":210}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "43409402394842098b88ddcff669394e":{
      "packageId":"43409402394842098b88ddcff669394e",
      "type":"Axure:Master",
      "name":"card header fullbredde",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2f60ad64d85f456cb59b0920d4d8b5c3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":750,
                "height":201}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a10337325f140c5b7666d1f0f8c5753",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":750,
                    "height":201}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u8.jpg"}}]}},
    "b51107c95ed542ad8315389bac1b78b4":{
      "packageId":"b51107c95ed542ad8315389bac1b78b4",
      "type":"Axure:Master",
      "name":"footer fullbredde",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f48046b10275499682e285dad9297209",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":750,
                "height":70},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"724ba94edc4e427e8caff0ce8f73eb1b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":750,
                    "height":70},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u33.png"}},
{
            "id":"55f22b18148542aba18a4f61d706663a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"19px",
              "fontWeight":"200",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":0,
                "y":22},
              "size":{
                "width":750,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dd6225c8eca54207ae5dbdfaadeab3f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"19px",
                  "fontWeight":"200",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":22},
                  "size":{
                    "width":750,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "fad38cd10ef74f2fb78d0da4f64dd769":{
      "scriptId":"u0"},
    "572918e8cf61418aafbb62512051936e":{
      "scriptId":"u1",
      "2f60ad64d85f456cb59b0920d4d8b5c3":{
        "scriptId":"u2"},
      "2a10337325f140c5b7666d1f0f8c5753":{
        "scriptId":"u3"}},
    "bce628fd9a6e4630b2e55284d47121a8":{
      "scriptId":"u4"},
    "c99eb5dff48a4734925236da6a7ab6bb":{
      "scriptId":"u5"},
    "94bbaeaa7e6947b29d20f227e617a345":{
      "scriptId":"u6"},
    "5aef67c39a774d9e88a5c0a5223efc70":{
      "scriptId":"u7"},
    "c06e6bdb25b54c8195e814630a776d52":{
      "scriptId":"u8"},
    "15fe570ac197495ab2eebbb0c810cb71":{
      "scriptId":"u9"},
    "ed7dd2efed6e40daac80d4000bdcb96c":{
      "scriptId":"u10"},
    "faa34d37bb1f4a29bd61c024033cf56c":{
      "scriptId":"u11"},
    "c26d62cefacf4f1881da6c245f3833b1":{
      "scriptId":"u12"},
    "1a927b15d3844848bdeb300a0c5992ef":{
      "scriptId":"u13"},
    "990bfdd9325e4316b034f1164896c69a":{
      "scriptId":"u14"},
    "ed0356309be640b2bdf2f0072781b133":{
      "scriptId":"u15"},
    "cd19cad400754cb88a43c6d5ad823f77":{
      "scriptId":"u16"},
    "20805ea394dc49d990aeb954252d1f9c":{
      "scriptId":"u17",
      "f48046b10275499682e285dad9297209":{
        "scriptId":"u18"},
      "724ba94edc4e427e8caff0ce8f73eb1b":{
        "scriptId":"u19"},
      "55f22b18148542aba18a4f61d706663a":{
        "scriptId":"u20"},
      "dd6225c8eca54207ae5dbdfaadeab3f4":{
        "scriptId":"u21"}},
    "83a933fa2e954fe09f5fa9e1a578cd66":{
      "scriptId":"u22"},
    "341e6126ebf844eaa72affdb544e9bd0":{
      "scriptId":"u23"},
    "3dc86850bf5b4b9c8ae07adf0ea8ed5f":{
      "scriptId":"u24"},
    "0ffe7b8bb31041b4ba60dad9a4adf422":{
      "scriptId":"u25"},
    "b223da822b9540acb125b020a03f5132":{
      "scriptId":"u26"},
    "e135bd904e294a068fc72455c721de36":{
      "scriptId":"u27"}}});