$axure.loadCurrentPage({
  "url":"velkommen_6.html",
  "generationDate":new Date(1400832043951.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"10546c27d9f048dfa2949182f0f94d69",
    "type":"Axure:Page",
    "name":"velkommen",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b66713c9cb746faaea7152a3f199e3b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2b40fb19f33c450284c7533e94ceefb7"},
{
          "id":"5ddb37003fbd4622b3080b079976d9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":150},
            "size":{
              "width":580,
              "height":420},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22209f2983394fe0a1ac365e72dcab40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":150},
                "size":{
                  "width":580,
                  "height":420},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/velkommen/u3.png"}},
{
          "id":"8b1c9cc57d4948ce85e084b1a9e31521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontSize":"34px",
            "fontWeight":"900",
            "location":{
              "x":120,
              "y":150},
            "size":{
              "width":490,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169bee24748c4e5eb8343ae57d6ce259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontSize":"34px",
                "fontWeight":"900",
                "location":{
                  "x":120,
                  "y":150},
                "size":{
                  "width":490,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tilgang_login_-_responsive_view/u5.png"}},
{
          "id":"c512aaf2c7674daf9029f8ec3ed9c489",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "paddingTop":"20",
            "paddingBottom":"20",
            "location":{
              "x":100,
              "y":210},
            "size":{
              "width":540,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e24ae10884a48d19297211bec8059b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "paddingTop":"20",
                "paddingBottom":"20",
                "location":{
                  "x":100,
                  "y":210},
                "size":{
                  "width":540,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd8eb7654e4342ae9cb4c24c205759df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":332,
              "y":279},
            "size":{
              "width":68,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f639057820724b6ba2972b62c24fc58c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":332,
                  "y":279},
                "size":{
                  "width":68,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bruker_opprettet/u7.png"}},
{
          "id":"26b52c7ac6da461792167f2566bac0e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "paddingTop":"20",
            "paddingBottom":"20",
            "location":{
              "x":100,
              "y":360},
            "size":{
              "width":540,
              "height":190},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4305ce3ebea4bbebb06f4c703670fe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "paddingTop":"20",
                "paddingBottom":"20",
                "location":{
                  "x":100,
                  "y":360},
                "size":{
                  "width":540,
                  "height":190},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/velkommen/u11.png"}},
{
          "id":"36ad7a73ad714d8dafa33f6593b1c8eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":377},
            "size":{
              "width":44,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b655e7e568c44cccbfa7e06bfaeec754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":377},
                "size":{
                  "width":44,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/velkommen/u13.png"}},
{
          "id":"425451cd55d1418191add6e2af2846a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":259,
              "y":380},
            "size":{
              "width":275,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bffda971bd8402cb221da9f5a88339b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":259,
                  "y":380},
                "size":{
                  "width":275,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"456b038b826143d391d1cf25e8107fca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "location":{
              "x":118,
              "y":417},
            "size":{
              "width":502,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbcfbc2526014af59cb902f97067d31e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "location":{
                  "x":118,
                  "y":417},
                "size":{
                  "width":502,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3de5c8694454b87aeb2a104e4c8a5a2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":270},
            "size":{
              "width":90,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open dit du ville in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dit_du_ville_6.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "2b40fb19f33c450284c7533e94ceefb7":{
      "packageId":"2b40fb19f33c450284c7533e94ceefb7",
      "type":"Axure:Master",
      "name":"newspaper-header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f116adf1346348c589d6534e6e84206f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":753,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16de1730a3c245c88590db8c75a43f16",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":753,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/tilgang_login_-_responsive_view/u1.jpg"}}]}}},
  "objectPaths":{
    "3b66713c9cb746faaea7152a3f199e3b":{
      "scriptId":"u0",
      "f116adf1346348c589d6534e6e84206f":{
        "scriptId":"u1"},
      "16de1730a3c245c88590db8c75a43f16":{
        "scriptId":"u2"}},
    "5ddb37003fbd4622b3080b079976d9d0":{
      "scriptId":"u3"},
    "22209f2983394fe0a1ac365e72dcab40":{
      "scriptId":"u4"},
    "8b1c9cc57d4948ce85e084b1a9e31521":{
      "scriptId":"u5"},
    "169bee24748c4e5eb8343ae57d6ce259":{
      "scriptId":"u6"},
    "c512aaf2c7674daf9029f8ec3ed9c489":{
      "scriptId":"u7"},
    "9e24ae10884a48d19297211bec8059b2":{
      "scriptId":"u8"},
    "cd8eb7654e4342ae9cb4c24c205759df":{
      "scriptId":"u9"},
    "f639057820724b6ba2972b62c24fc58c":{
      "scriptId":"u10"},
    "26b52c7ac6da461792167f2566bac0e9":{
      "scriptId":"u11"},
    "c4305ce3ebea4bbebb06f4c703670fe5":{
      "scriptId":"u12"},
    "36ad7a73ad714d8dafa33f6593b1c8eb":{
      "scriptId":"u13"},
    "b655e7e568c44cccbfa7e06bfaeec754":{
      "scriptId":"u14"},
    "425451cd55d1418191add6e2af2846a4":{
      "scriptId":"u15"},
    "7bffda971bd8402cb221da9f5a88339b":{
      "scriptId":"u16"},
    "456b038b826143d391d1cf25e8107fca":{
      "scriptId":"u17"},
    "fbcfbc2526014af59cb902f97067d31e":{
      "scriptId":"u18"},
    "a3de5c8694454b87aeb2a104e4c8a5a2":{
      "scriptId":"u19"}}});