$axure.loadCurrentPage({
  "url":"insentivside_8.html",
  "generationDate":new Date(1400832045263.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7994430b4f554593ac4973621fca7849",
    "type":"Axure:Page",
    "name":"insentivside",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a54d312a55774fd9b2911edae87405b4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"c4e0ef4a795e49f8825f93a20a448ad4"},
{
          "id":"c7144fc0c873465c82b94e41e3849aa8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":546,
              "y":733},
            "size":{
              "width":188,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open tilgang/login in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"tilgang_login_7.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "c4e0ef4a795e49f8825f93a20a448ad4":{
      "packageId":"c4e0ef4a795e49f8825f93a20a448ad4",
      "type":"Axure:Master",
      "name":"insentivside MED tidsbegrensning",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bf08a7d502694e81b8ba895c7e873b93",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
              "fontWeight":"900",
              "horizontalAlignment":"center",
              "location":{
                "x":0,
                "y":241},
              "size":{
                "width":740,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e54cc0a96b554257b65e8b8cb6b5ddbb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                  "fontWeight":"900",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":0,
                    "y":241},
                  "size":{
                    "width":740,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"78bb22e1c83945f988c09ba3a8220a34",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":486},
              "size":{
                "width":750,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFC9C9C9}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u2_line.png"}},
{
            "id":"04f480ebf7fa4f1ab3fda10766db6790",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
              "fontSize":"19px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":348,
                "y":581},
              "size":{
                "width":82,
                "height":40},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b38d630b3feb4648be8d03a00b5855e0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                  "fontSize":"19px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":348,
                    "y":581},
                  "size":{
                    "width":82,
                    "height":40},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u3.png"}},
{
            "id":"0b7bd5ce2ad04d7687c5c4bd2323446d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":295,
                "y":589},
              "size":{
                "width":46,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f2b69a41e38c4cb484640c9bdaac050f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":295,
                    "y":589},
                  "size":{
                    "width":46,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u5.jpg"}},
{
            "id":"d1232abc749e40888d5ab0fb55498d82",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":-2,
                "y":10}},
            "adaptiveStyles":{
},
            "masterId":"43409402394842098b88ddcff669394e"},
{
            "id":"989c5b7ec2c343c2ad7de26cc81d3673",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"16px",
              "fontWeight":"200",
              "horizontalAlignment":"center",
              "location":{
                "x":80,
                "y":400},
              "size":{
                "width":580,
                "height":63}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f7604d8ec03e4bbd8262df65ed5052a7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":80,
                    "y":400},
                  "size":{
                    "width":580,
                    "height":63}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2a1da45f16854fa58c8a9f5ce1c8884e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"19px",
              "fontWeight":"200",
              "underline":true,
              "horizontalAlignment":"right",
              "location":{
                "x":-10,
                "y":331},
              "size":{
                "width":350,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a80985e7bfb84205818de82df3a8f41a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"19px",
                  "fontWeight":"200",
                  "underline":true,
                  "horizontalAlignment":"right",
                  "location":{
                    "x":-10,
                    "y":331},
                  "size":{
                    "width":350,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"58b171656dea43c3a364cf33b229e833",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"19px",
              "fontWeight":"200",
              "underline":true,
              "location":{
                "x":400,
                "y":331},
              "size":{
                "width":350,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a325ccbed42405c88c610432efb8910",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"19px",
                  "fontWeight":"200",
                  "underline":true,
                  "location":{
                    "x":400,
                    "y":331},
                  "size":{
                    "width":350,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"935dea9a7053463b8daee36cf7986e4b",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":365,
                "y":320},
              "size":{
                "width":10,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFC9C9C9}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u16_line.png"}},
{
            "id":"ac575aedaff04fb9ac38ff854cbe932f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
              "fontWeight":"900",
              "horizontalAlignment":"center",
              "location":{
                "x":0,
                "y":506},
              "size":{
                "width":740,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cb3e8c8996b14d05a69b23068fe04b8a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                  "fontWeight":"900",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":0,
                    "y":506},
                  "size":{
                    "width":740,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2388ca7e7e9345708a64b47cf9eb3e8f",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":646},
              "size":{
                "width":750,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFC9C9C9}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u2_line.png"}},
{
            "id":"21a6157cc0f04c33a95cbae66a110ad1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
              "fontWeight":"900",
              "horizontalAlignment":"center",
              "location":{
                "x":0,
                "y":669},
              "size":{
                "width":740,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a18329d949b44a86a23343932fcaebaa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                  "fontWeight":"900",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":0,
                    "y":669},
                  "size":{
                    "width":740,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"50b7bbe0da494ff48a6712006d3a06ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "horizontalAlignment":"center",
              "location":{
                "x":80,
                "y":828},
              "size":{
                "width":580,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"69ed1774a7574c4c9918c607b142b6d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":80,
                    "y":828},
                  "size":{
                    "width":580,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"355f6bb02741435cb7eb33876275ad39",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"19px",
              "fontWeight":"200",
              "underline":true,
              "horizontalAlignment":"center",
              "location":{
                "x":11,
                "y":759},
              "size":{
                "width":180,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05c3b3b967a34f50a7434615877a88a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"19px",
                  "fontWeight":"200",
                  "underline":true,
                  "horizontalAlignment":"center",
                  "location":{
                    "x":11,
                    "y":759},
                  "size":{
                    "width":180,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"14539da98cb24124a71c1caaed8c8e62",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"19px",
              "fontWeight":"200",
              "underline":true,
              "horizontalAlignment":"center",
              "location":{
                "x":222,
                "y":759},
              "size":{
                "width":295,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"befce86fd4ad46b9a2ee41429cd3c2cd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"19px",
                  "fontWeight":"200",
                  "underline":true,
                  "horizontalAlignment":"center",
                  "location":{
                    "x":222,
                    "y":759},
                  "size":{
                    "width":295,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"280b4bd36dc24f9cb09599932232f459",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":201,
                "y":748},
              "size":{
                "width":10,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFC9C9C9}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u16_line.png"}},
{
            "id":"c8bbd381ed624bccbe2358a105bd5a29",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"19px",
              "fontWeight":"200",
              "underline":true,
              "horizontalAlignment":"center",
              "location":{
                "x":550,
                "y":759},
              "size":{
                "width":181,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"36924eeda4874ba898021f818485d128",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"19px",
                  "fontWeight":"200",
                  "underline":true,
                  "horizontalAlignment":"center",
                  "location":{
                    "x":550,
                    "y":759},
                  "size":{
                    "width":181,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c62b6797e0cc48d8ab2d39288a135074",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":529,
                "y":748},
              "size":{
                "width":10,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFC9C9C9}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u16_line.png"}},
{
            "id":"f560a8d2d8174695a3de5e79cec73cf8",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":901}},
            "adaptiveStyles":{
},
            "masterId":"b51107c95ed542ad8315389bac1b78b4"}]}},
    "43409402394842098b88ddcff669394e":{
      "packageId":"43409402394842098b88ddcff669394e",
      "type":"Axure:Master",
      "name":"card header fullbredde",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2f60ad64d85f456cb59b0920d4d8b5c3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":750,
                "height":201}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a10337325f140c5b7666d1f0f8c5753",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":750,
                    "height":201}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u8.jpg"}}]}},
    "b51107c95ed542ad8315389bac1b78b4":{
      "packageId":"b51107c95ed542ad8315389bac1b78b4",
      "type":"Axure:Master",
      "name":"footer fullbredde",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f48046b10275499682e285dad9297209",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":750,
                "height":70},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"724ba94edc4e427e8caff0ce8f73eb1b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":750,
                    "height":70},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/insentivside__med_tidsbegrensning_-_responsive_vie/u33.png"}},
{
            "id":"55f22b18148542aba18a4f61d706663a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
              "fontSize":"19px",
              "fontWeight":"200",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":0,
                "y":22},
              "size":{
                "width":750,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dd6225c8eca54207ae5dbdfaadeab3f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Roboto-Light', 'Roboto Light', 'Roboto'",
                  "fontSize":"19px",
                  "fontWeight":"200",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":22},
                  "size":{
                    "width":750,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "a54d312a55774fd9b2911edae87405b4":{
      "scriptId":"u0",
      "bf08a7d502694e81b8ba895c7e873b93":{
        "scriptId":"u1"},
      "e54cc0a96b554257b65e8b8cb6b5ddbb":{
        "scriptId":"u2"},
      "78bb22e1c83945f988c09ba3a8220a34":{
        "scriptId":"u3"},
      "04f480ebf7fa4f1ab3fda10766db6790":{
        "scriptId":"u4"},
      "b38d630b3feb4648be8d03a00b5855e0":{
        "scriptId":"u5"},
      "0b7bd5ce2ad04d7687c5c4bd2323446d":{
        "scriptId":"u6"},
      "f2b69a41e38c4cb484640c9bdaac050f":{
        "scriptId":"u7"},
      "d1232abc749e40888d5ab0fb55498d82":{
        "scriptId":"u8",
        "2f60ad64d85f456cb59b0920d4d8b5c3":{
          "scriptId":"u9"},
        "2a10337325f140c5b7666d1f0f8c5753":{
          "scriptId":"u10"}},
      "989c5b7ec2c343c2ad7de26cc81d3673":{
        "scriptId":"u11"},
      "f7604d8ec03e4bbd8262df65ed5052a7":{
        "scriptId":"u12"},
      "2a1da45f16854fa58c8a9f5ce1c8884e":{
        "scriptId":"u13"},
      "a80985e7bfb84205818de82df3a8f41a":{
        "scriptId":"u14"},
      "58b171656dea43c3a364cf33b229e833":{
        "scriptId":"u15"},
      "7a325ccbed42405c88c610432efb8910":{
        "scriptId":"u16"},
      "935dea9a7053463b8daee36cf7986e4b":{
        "scriptId":"u17"},
      "ac575aedaff04fb9ac38ff854cbe932f":{
        "scriptId":"u18"},
      "cb3e8c8996b14d05a69b23068fe04b8a":{
        "scriptId":"u19"},
      "2388ca7e7e9345708a64b47cf9eb3e8f":{
        "scriptId":"u20"},
      "21a6157cc0f04c33a95cbae66a110ad1":{
        "scriptId":"u21"},
      "a18329d949b44a86a23343932fcaebaa":{
        "scriptId":"u22"},
      "50b7bbe0da494ff48a6712006d3a06ca":{
        "scriptId":"u23"},
      "69ed1774a7574c4c9918c607b142b6d3":{
        "scriptId":"u24"},
      "355f6bb02741435cb7eb33876275ad39":{
        "scriptId":"u25"},
      "05c3b3b967a34f50a7434615877a88a9":{
        "scriptId":"u26"},
      "14539da98cb24124a71c1caaed8c8e62":{
        "scriptId":"u27"},
      "befce86fd4ad46b9a2ee41429cd3c2cd":{
        "scriptId":"u28"},
      "280b4bd36dc24f9cb09599932232f459":{
        "scriptId":"u29"},
      "c8bbd381ed624bccbe2358a105bd5a29":{
        "scriptId":"u30"},
      "36924eeda4874ba898021f818485d128":{
        "scriptId":"u31"},
      "c62b6797e0cc48d8ab2d39288a135074":{
        "scriptId":"u32"},
      "f560a8d2d8174695a3de5e79cec73cf8":{
        "scriptId":"u33",
        "f48046b10275499682e285dad9297209":{
          "scriptId":"u34"},
        "724ba94edc4e427e8caff0ce8f73eb1b":{
          "scriptId":"u35"},
        "55f22b18148542aba18a4f61d706663a":{
          "scriptId":"u36"},
        "dd6225c8eca54207ae5dbdfaadeab3f4":{
          "scriptId":"u37"}}},
    "c7144fc0c873465c82b94e41e3849aa8":{
      "scriptId":"u38"}}});