$axure.loadCurrentPage({
  "url":"startside_for_prototypen.html",
  "generationDate":new Date(1400834542272.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"784949174d66432cbba045826b3e090a",
    "type":"Axure:Page",
    "name":"startside for prototypen",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c1462a23fdfc43f989143bd2e26f9d1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":365,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ab1895045994d0388f8989547805f84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":365,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9b449331f814e18b47569e880f3a5e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":480,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b47c2fe9de5e4c5dbf4d08b7e4d5f0b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":480,
                  "height":210}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67f1a510a5484381b526e46e41fa81a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009900},
            "paddingTop":"20",
            "paddingBottom":"20",
            "location":{
              "x":20,
              "y":290},
            "size":{
              "width":420,
              "height":90},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"decefaaefa1a42f3a647df99e2ad6aa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009900},
                "paddingTop":"20",
                "paddingBottom":"20",
                "location":{
                  "x":20,
                  "y":290},
                "size":{
                  "width":420,
                  "height":90},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/startside_for_prototypen/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c1462a23fdfc43f989143bd2e26f9d1c":{
      "scriptId":"u0"},
    "0ab1895045994d0388f8989547805f84":{
      "scriptId":"u1"},
    "a9b449331f814e18b47569e880f3a5e1":{
      "scriptId":"u2"},
    "b47c2fe9de5e4c5dbf4d08b7e4d5f0b9":{
      "scriptId":"u3"},
    "67f1a510a5484381b526e46e41fa81a9":{
      "scriptId":"u4"},
    "decefaaefa1a42f3a647df99e2ad6aa8":{
      "scriptId":"u5"}}});