$axure.loadCurrentPage({
  "url":"feilkort__familiel_p_for_andre_gang.html",
  "generationDate":new Date(1398860913429.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fc0632d2cc624e439d9dae81a87a5506",
    "type":"Axure:Page",
    "name":"feilkort: familieløp for ANDRE gang",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b66713c9cb746faaea7152a3f199e3b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2b40fb19f33c450284c7533e94ceefb7"},
{
          "id":"5ddb37003fbd4622b3080b079976d9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":150},
            "size":{
              "width":580,
              "height":210},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22209f2983394fe0a1ac365e72dcab40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":150},
                "size":{
                  "width":580,
                  "height":210},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/feilkort__familiel_p_for_andre_gang/u3.png"}},
{
          "id":"8b1c9cc57d4948ce85e084b1a9e31521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontSize":"34px",
            "fontWeight":"900",
            "location":{
              "x":120,
              "y":150},
            "size":{
              "width":490,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169bee24748c4e5eb8343ae57d6ce259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontSize":"34px",
                "fontWeight":"900",
                "location":{
                  "x":120,
                  "y":150},
                "size":{
                  "width":490,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u19.png"}},
{
          "id":"ce841c68e270422fbe05b834ba782bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":332,
              "y":301},
            "size":{
              "width":68,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8325cc45365d44979604392a79c124d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":332,
                  "y":301},
                "size":{
                  "width":68,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bruker_opprettet/u7.png"}},
{
          "id":"f130437c30834808947858274e0805a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "paddingTop":"20",
            "paddingBottom":"20",
            "location":{
              "x":100,
              "y":220},
            "size":{
              "width":540,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d87f14f85844a97aa25ab0cfdac2fa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "paddingTop":"20",
                "paddingBottom":"20",
                "location":{
                  "x":100,
                  "y":220},
                "size":{
                  "width":540,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cbc163cd56d42d98a5ffcc855556b0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":450},
            "size":{
              "width":2398,
              "height":1201},
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"788380020a35474bba6150d053cdc4f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":450},
                "size":{
                  "width":2398,
                  "height":1201},
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/feilkort__familiel_p_for_andre_gang/u11.png"}},
{
          "id":"26000ef9b587425fa74dfb57f3d4d286",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1040,
              "y":1200},
            "size":{
              "width":380,
              "height":380},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c2d2d5a45f9441d994e16e0c94a6ad2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1040,
                  "y":1200},
                "size":{
                  "width":380,
                  "height":380},
                "borderWidth":"5",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/feilkort__systemfeil/u13.png"}},
{
          "id":"f13863251be744c4831f530df88cae3e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":236},
            "size":{
              "width":10,
              "height":1120},
            "rotation":"324",
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC00}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/feilkort__familiel_p_for_andre_gang/u15_line.png"}}]}},
  "masters":{
    "2b40fb19f33c450284c7533e94ceefb7":{
      "packageId":"2b40fb19f33c450284c7533e94ceefb7",
      "type":"Axure:Master",
      "name":"newspaper-header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f116adf1346348c589d6534e6e84206f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":753,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16de1730a3c245c88590db8c75a43f16",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":753,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/tilgang_login/u1.jpg"}}]}}},
  "objectPaths":{
    "3b66713c9cb746faaea7152a3f199e3b":{
      "scriptId":"u0",
      "f116adf1346348c589d6534e6e84206f":{
        "scriptId":"u1"},
      "16de1730a3c245c88590db8c75a43f16":{
        "scriptId":"u2"}},
    "5ddb37003fbd4622b3080b079976d9d0":{
      "scriptId":"u3"},
    "22209f2983394fe0a1ac365e72dcab40":{
      "scriptId":"u4"},
    "8b1c9cc57d4948ce85e084b1a9e31521":{
      "scriptId":"u5"},
    "169bee24748c4e5eb8343ae57d6ce259":{
      "scriptId":"u6"},
    "ce841c68e270422fbe05b834ba782bd4":{
      "scriptId":"u7"},
    "8325cc45365d44979604392a79c124d2":{
      "scriptId":"u8"},
    "f130437c30834808947858274e0805a1":{
      "scriptId":"u9"},
    "9d87f14f85844a97aa25ab0cfdac2fa7":{
      "scriptId":"u10"},
    "9cbc163cd56d42d98a5ffcc855556b0d":{
      "scriptId":"u11"},
    "788380020a35474bba6150d053cdc4f9":{
      "scriptId":"u12"},
    "26000ef9b587425fa74dfb57f3d4d286":{
      "scriptId":"u13"},
    "7c2d2d5a45f9441d994e16e0c94a6ad2":{
      "scriptId":"u14"},
    "f13863251be744c4831f530df88cae3e":{
      "scriptId":"u15"}}});