$axure.loadCurrentPage({
  "url":"oversikt.html",
  "generationDate":new Date(1398865214469.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b70d08be38a146b6b4a7a13e59b85d84",
    "type":"Axure:Page",
    "name":"oversikt",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF2F2F2},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b4c2c8a253e445d1a0ea438b6fa9fd2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":710},
            "size":{
              "width":980,
              "height":330},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1470fbddb04b82a1e975dc2f2531c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":710},
                "size":{
                  "width":980,
                  "height":330},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/oversikt/u0.png"}},
{
          "id":"f6570c2fa9974261a8884ea384550060",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":260},
            "size":{
              "width":980,
              "height":420},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80e9a89c6fc7462fb6dfbf1c4f4db830",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":260},
                "size":{
                  "width":980,
                  "height":420},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/oversikt/u2.png"}},
{
          "id":"1a8f02526bcb46eaa98464bbd13a0282",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-3,
              "y":-5},
            "size":{
              "width":1053,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d5ce9175e92413ca78b11a543c1e035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-3,
                  "y":-5},
                "size":{
                  "width":1053,
                  "height":92}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/oversikt/u4.jpg"}},
{
          "id":"f59461b2a088496b8057b17f64f05d17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
            "fontSize":"24px",
            "location":{
              "x":58,
              "y":291},
            "size":{
              "width":922,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f5d0b1eb36b41fb8a33d491069fc615",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                "fontSize":"24px",
                "location":{
                  "x":58,
                  "y":291},
                "size":{
                  "width":922,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb724f33e9bb48a8a7ddaeff39f6c06b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "location":{
              "x":58,
              "y":488},
            "size":{
              "width":280,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214a893cf07a4f67aadbde287796b5dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "location":{
                  "x":58,
                  "y":488},
                "size":{
                  "width":280,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af65c591392640b3b67a3ffacc1feabe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "location":{
              "x":58,
              "y":418},
            "size":{
              "width":280,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c396619dab8f4be8b99b15c75c759c5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "location":{
                  "x":58,
                  "y":418},
                "size":{
                  "width":280,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a52ff1b4387349959a76cd47d8816dcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "location":{
              "x":58,
              "y":558},
            "size":{
              "width":280,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54a72dec7f9d40488aa017ffc9dd4495",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "location":{
                  "x":58,
                  "y":558},
                "size":{
                  "width":280,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"113a104b08714b32943ce7d45060b228",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "location":{
              "x":58,
              "y":348},
            "size":{
              "width":280,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cea7e878ac34bfa8d7ffbacd6d6c762",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "location":{
                  "x":58,
                  "y":348},
                "size":{
                  "width":280,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"667a99f7bf8049b088571b91e2391f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "underline":true,
            "location":{
              "x":58,
              "y":627},
            "size":{
              "width":114,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e92794788bfd464190ffa4345fdad8bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "underline":true,
                "location":{
                  "x":58,
                  "y":627},
                "size":{
                  "width":114,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"970d25e70d8e48e5b0cdac754b845598",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
            "fontSize":"24px",
            "location":{
              "x":58,
              "y":735},
            "size":{
              "width":922,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdf0db0759bd499787a68e81e155ad73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                "fontSize":"24px",
                "location":{
                  "x":58,
                  "y":735},
                "size":{
                  "width":922,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6d14c6d98844a1998ab89d00ad156d7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":330},
            "size":{
              "width":920,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEEEEEE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/oversikt/u20_line.png"}},
{
          "id":"ad044d0133464c0abbd57cd8a0116e32",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":780},
            "size":{
              "width":920,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEEEEEE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/oversikt/u20_line.png"}},
{
          "id":"b948b2bead924e91a9abf8686e068015",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEDF7F1},
            "location":{
              "x":60,
              "y":810},
            "size":{
              "width":920,
              "height":200},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"159e6bf092c447a58df93d33ccacd03d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEDF7F1},
                "location":{
                  "x":60,
                  "y":810},
                "size":{
                  "width":920,
                  "height":200},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/oversikt/u22.png"}},
{
          "id":"5e5c46d54e454010b6809adaf48a0896",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
            "fontSize":"19px",
            "location":{
              "x":82,
              "y":828},
            "size":{
              "width":878,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"765e6755c8b54e3fa79bd634ccbc1462",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                "fontSize":"19px",
                "location":{
                  "x":82,
                  "y":828},
                "size":{
                  "width":878,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"945c4450d03c4d41a3e0d4b76f25f3c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "location":{
              "x":82,
              "y":870},
            "size":{
              "width":251,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8897bf7dc6cf45f4b01242e5d3ea3ec6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "location":{
                  "x":82,
                  "y":870},
                "size":{
                  "width":251,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c9b574df85645409f438a608345e4c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "location":{
              "x":82,
              "y":940},
            "size":{
              "width":408,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc6db57b2c141f782ea3ff35828c33a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "location":{
                  "x":82,
                  "y":940},
                "size":{
                  "width":408,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6600fce9217443d9b2d50fdab634c599",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1260}},
          "adaptiveStyles":{
},
          "masterId":"c659a0f679d04fa3be4f0c9bb83a92a5"},
{
          "id":"e7fe47b8e6f3481b8a291cd52bfe12ec",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":160}},
          "adaptiveStyles":{
},
          "masterId":"69ae6806ee54475b974f31d4bce44331"},
{
          "id":"0ff3758664d049479ba92e842dc941f8",
          "label":"familiemedlemmer",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":1060},
            "size":{
              "width":980,
              "height":170}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1a893fac3ffc41bf992024219a830222",
              "label":"normal",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6b6fcaae23c147a58451f009b7508bc1",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":980,
                      "height":170},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d471220ab112430f8d1098c9ac7867e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":980,
                          "height":170},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u47.png"}},
{
                  "id":"2bdd23492b5544ffb2b6fc50f22ff163",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"19px",
                    "location":{
                      "x":92,
                      "y":110},
                    "size":{
                      "width":128,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eac4ff449d744f6695ed12c489301c16",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"19px",
                        "location":{
                          "x":92,
                          "y":110},
                        "size":{
                          "width":128,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7a5800f74a6348909d0728627d13f823",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"19px",
                    "location":{
                      "x":302,
                      "y":110},
                    "size":{
                      "width":158,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c2811a26fee5459685b96a3a3f740ce5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"19px",
                        "location":{
                          "x":302,
                          "y":110},
                        "size":{
                          "width":158,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"73a62805a8464e19b1f073793535c1e8",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"50px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "paddingTop":"5",
                    "location":{
                      "x":480,
                      "y":94},
                    "size":{
                      "width":50,
                      "height":50},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"969bfdf7fa6240c99aa8599b277f1e9d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"50px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "paddingTop":"5",
                        "location":{
                          "x":480,
                          "y":94},
                        "size":{
                          "width":50,
                          "height":50},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u53.png"}},
{
                  "id":"f132b057c7aa4a83bc9a8bf3427a5fe2",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"19px",
                    "location":{
                      "x":542,
                      "y":110},
                    "size":{
                      "width":208,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9b66a90ba2cb4e90bd3bb596ffce3ca2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"19px",
                        "location":{
                          "x":542,
                          "y":110},
                        "size":{
                          "width":208,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"14f9438f679b449ab532922bdc399ef9",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                    "fontSize":"24px",
                    "location":{
                      "x":28,
                      "y":20},
                    "size":{
                      "width":922,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89ddc17f05b644408b5eb507822aead1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                        "fontSize":"24px",
                        "location":{
                          "x":28,
                          "y":20},
                        "size":{
                          "width":922,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3aaecd971a3241b1b55943e2cfe93e12",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":66},
                    "size":{
                      "width":920,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEEEEEE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/oversikt/u20_line.png"}},
{
                  "id":"1922ff205e824d679cd58baece15a01c",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":24,
                      "y":90},
                    "size":{
                      "width":64,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b48cbf77e01412d802a6eca3399c147",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":24,
                          "y":90},
                        "size":{
                          "width":64,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u60.png"}},
{
                  "id":"9ad651fee56e42d6954a28aee57f9984",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":232,
                      "y":90},
                    "size":{
                      "width":64,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a75cd3fd6d8b431dad1375234148062e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":232,
                          "y":90},
                        "size":{
                          "width":64,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u60.png"}},
{
                  "id":"7e1e40c9dccb4c119364ecdeb2d7aeac",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"19px",
                    "underline":true,
                    "horizontalAlignment":"right",
                    "location":{
                      "x":840,
                      "y":28},
                    "size":{
                      "width":110,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac784b189d6f4306b40f95bd62b6b25b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"19px",
                        "underline":true,
                        "horizontalAlignment":"right",
                        "location":{
                          "x":840,
                          "y":28},
                        "size":{
                          "width":110,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set familiemedlemmer to endre",
                              "panelsToStates":[{
                                  "panelPath":["0ff3758664d049479ba92e842dc941f8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"7d19c2cc51dc44eaad1d57445d63bcd1",
              "label":"endre",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"39760a805a304dbdb305b9d8333a46f1",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":980,
                      "height":170},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3179d4fd50ed494d92d53b35a8b78560",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":980,
                          "height":170},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u47.png"}},
{
                  "id":"d1174c9a5c4c4c16858ef53118c9514c",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"19px",
                    "location":{
                      "x":92,
                      "y":110},
                    "size":{
                      "width":128,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"416557cd87664b61a647f99c3c57a079",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"19px",
                        "location":{
                          "x":92,
                          "y":110},
                        "size":{
                          "width":128,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"926673b9f9884c5f8980dc3c0bef61e8",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"19px",
                    "location":{
                      "x":302,
                      "y":110},
                    "size":{
                      "width":158,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"14e569bc842f43fb968baeadca3b4803",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"19px",
                        "location":{
                          "x":302,
                          "y":110},
                        "size":{
                          "width":158,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"395032646ad5440a9e43bbc8234f36b7",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"50px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "paddingTop":"5",
                    "location":{
                      "x":480,
                      "y":94},
                    "size":{
                      "width":50,
                      "height":50},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"69176f5d8cc94fa7b2086f93e3c78933",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"50px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "paddingTop":"5",
                        "location":{
                          "x":480,
                          "y":94},
                        "size":{
                          "width":50,
                          "height":50},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u53.png"}},
{
                  "id":"2195891900a14663ae54f25dfd50e456",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"19px",
                    "location":{
                      "x":542,
                      "y":110},
                    "size":{
                      "width":208,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cfc81a13aa6e4fc6b54e066711966a80",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"19px",
                        "location":{
                          "x":542,
                          "y":110},
                        "size":{
                          "width":208,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8c5441a42fe246d5a1f9690fe52ad882",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                    "fontSize":"24px",
                    "location":{
                      "x":28,
                      "y":20},
                    "size":{
                      "width":922,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"20582ec4a7674a5392fbc9df713f09f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                        "fontSize":"24px",
                        "location":{
                          "x":28,
                          "y":20},
                        "size":{
                          "width":922,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1531a8536a04423e963b25c19ca5f35b",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":66},
                    "size":{
                      "width":920,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEEEEEE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/oversikt/u20_line.png"}},
{
                  "id":"7baef41763744286a21fa748a0b361ca",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":24,
                      "y":90},
                    "size":{
                      "width":64,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0b074067f4a64a2dadd7ea103c2908ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":24,
                          "y":90},
                        "size":{
                          "width":64,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u60.png"}},
{
                  "id":"6075a987cf334f2dac43c4eb95c11419",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":232,
                      "y":90},
                    "size":{
                      "width":64,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"191ed4e431bf4a948c11bcfcf5d84af4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":232,
                          "y":90},
                        "size":{
                          "width":64,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u60.png"}},
{
                  "id":"bb4250507fdc41e792d9805e5d2bbed6",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"19px",
                    "underline":true,
                    "horizontalAlignment":"right",
                    "location":{
                      "x":792,
                      "y":28},
                    "size":{
                      "width":158,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"479c4343e44c40c5bf5ad8968908b209",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"19px",
                        "underline":true,
                        "horizontalAlignment":"right",
                        "location":{
                          "x":792,
                          "y":28},
                        "size":{
                          "width":158,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set familiemedlemmer to normal",
                              "panelsToStates":[{
                                  "panelPath":["0ff3758664d049479ba92e842dc941f8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"876e009aab3a45128136c30b11135d91",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":260,
                      "y":90},
                    "size":{
                      "width":34,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4a73eef52234ff49f99e1b203b679b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":260,
                          "y":90},
                        "size":{
                          "width":34,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u85.png"}},
{
                  "id":"42aa3abadac746b08a6908fd12527b20",
                  "label":"",
                  "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":51,
                      "y":90},
                    "size":{
                      "width":34,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"14aaa6380dc742db855b722caa0f5919",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0ff3758664d049479ba92e842dc941f8",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":51,
                          "y":90},
                        "size":{
                          "width":34,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/oversikt/u85.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "c659a0f679d04fa3be4f0c9bb83a92a5":{
      "packageId":"c659a0f679d04fa3be4f0c9bb83a92a5",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa0ca7c8a63c4fd698183d08b0ff05e4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF434343},
              "size":{
                "width":1130,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"284f9be7fc4a433fb44b893ec408a26a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF434343},
                  "size":{
                    "width":1130,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/oversikt/u31.png"}},
{
            "id":"2fc7f94f44854415ab9e3c40eb4dcde6",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"40px",
              "location":{
                "x":30,
                "y":38},
              "size":{
                "width":65,
                "height":49}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a841b7cca0145c7affcdf3c4d3398fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"40px",
                  "location":{
                    "x":30,
                    "y":38},
                  "size":{
                    "width":65,
                    "height":49}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"32ed36c9cdc142c58eb9a13f6aac752b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"19px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":130,
                "y":54},
              "size":{
                "width":890,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78b58fd08b6f4c858cc0fde0d1540747",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"19px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":130,
                    "y":54},
                  "size":{
                    "width":890,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c6c65c43030740ab9cb8c0e1d082d1a1",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":117,
                "y":43},
              "size":{
                "width":90,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open om aid in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"om_aid.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"57806af78fc74ed59ed355709d584671",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":43},
              "size":{
                "width":130,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open brukervilkår in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"brukervilk_r.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "69ae6806ee54475b974f31d4bce44331":{
      "packageId":"69ae6806ee54475b974f31d4bce44331",
      "type":"Axure:Master",
      "name":"header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c310211d63d941b7a63709b51e13d0d2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF605857},
              "size":{
                "width":980,
                "height":80},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b0dd075d4a13435bb38d36d36d355e2c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF605857},
                  "size":{
                    "width":980,
                    "height":80},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/oversikt/u40.png"}},
{
            "id":"bb403b174c84493fb4f494d656fe76be",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
              "fontSize":"34px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":150,
                "y":21},
              "size":{
                "width":580,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58960e18088740d6b430de5d372859ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                  "fontSize":"34px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":150,
                    "y":21},
                  "size":{
                    "width":580,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"55ded9c022034980874697e6ecf96b50",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"55px",
              "location":{
                "x":29,
                "y":7},
              "size":{
                "width":90,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"10fd560854464e449efe80171de9a593",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"55px",
                  "location":{
                    "x":29,
                    "y":7},
                  "size":{
                    "width":90,
                    "height":68}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open oversikt in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"oversikt.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "b4c2c8a253e445d1a0ea438b6fa9fd2e":{
      "scriptId":"u0"},
    "9d1470fbddb04b82a1e975dc2f2531c9":{
      "scriptId":"u1"},
    "f6570c2fa9974261a8884ea384550060":{
      "scriptId":"u2"},
    "80e9a89c6fc7462fb6dfbf1c4f4db830":{
      "scriptId":"u3"},
    "1a8f02526bcb46eaa98464bbd13a0282":{
      "scriptId":"u4"},
    "5d5ce9175e92413ca78b11a543c1e035":{
      "scriptId":"u5"},
    "f59461b2a088496b8057b17f64f05d17":{
      "scriptId":"u6"},
    "5f5d0b1eb36b41fb8a33d491069fc615":{
      "scriptId":"u7"},
    "bb724f33e9bb48a8a7ddaeff39f6c06b":{
      "scriptId":"u8"},
    "214a893cf07a4f67aadbde287796b5dd":{
      "scriptId":"u9"},
    "af65c591392640b3b67a3ffacc1feabe":{
      "scriptId":"u10"},
    "c396619dab8f4be8b99b15c75c759c5c":{
      "scriptId":"u11"},
    "a52ff1b4387349959a76cd47d8816dcb":{
      "scriptId":"u12"},
    "54a72dec7f9d40488aa017ffc9dd4495":{
      "scriptId":"u13"},
    "113a104b08714b32943ce7d45060b228":{
      "scriptId":"u14"},
    "2cea7e878ac34bfa8d7ffbacd6d6c762":{
      "scriptId":"u15"},
    "667a99f7bf8049b088571b91e2391f50":{
      "scriptId":"u16"},
    "e92794788bfd464190ffa4345fdad8bc":{
      "scriptId":"u17"},
    "970d25e70d8e48e5b0cdac754b845598":{
      "scriptId":"u18"},
    "cdf0db0759bd499787a68e81e155ad73":{
      "scriptId":"u19"},
    "a6d14c6d98844a1998ab89d00ad156d7":{
      "scriptId":"u20"},
    "ad044d0133464c0abbd57cd8a0116e32":{
      "scriptId":"u21"},
    "b948b2bead924e91a9abf8686e068015":{
      "scriptId":"u22"},
    "159e6bf092c447a58df93d33ccacd03d":{
      "scriptId":"u23"},
    "5e5c46d54e454010b6809adaf48a0896":{
      "scriptId":"u24"},
    "765e6755c8b54e3fa79bd634ccbc1462":{
      "scriptId":"u25"},
    "945c4450d03c4d41a3e0d4b76f25f3c7":{
      "scriptId":"u26"},
    "8897bf7dc6cf45f4b01242e5d3ea3ec6":{
      "scriptId":"u27"},
    "5c9b574df85645409f438a608345e4c9":{
      "scriptId":"u28"},
    "4bc6db57b2c141f782ea3ff35828c33a":{
      "scriptId":"u29"},
    "6600fce9217443d9b2d50fdab634c599":{
      "scriptId":"u30",
      "aa0ca7c8a63c4fd698183d08b0ff05e4":{
        "scriptId":"u31"},
      "284f9be7fc4a433fb44b893ec408a26a":{
        "scriptId":"u32"},
      "2fc7f94f44854415ab9e3c40eb4dcde6":{
        "scriptId":"u33"},
      "5a841b7cca0145c7affcdf3c4d3398fa":{
        "scriptId":"u34"},
      "32ed36c9cdc142c58eb9a13f6aac752b":{
        "scriptId":"u35"},
      "78b58fd08b6f4c858cc0fde0d1540747":{
        "scriptId":"u36"},
      "c6c65c43030740ab9cb8c0e1d082d1a1":{
        "scriptId":"u37"},
      "57806af78fc74ed59ed355709d584671":{
        "scriptId":"u38"}},
    "e7fe47b8e6f3481b8a291cd52bfe12ec":{
      "scriptId":"u39",
      "c310211d63d941b7a63709b51e13d0d2":{
        "scriptId":"u40"},
      "b0dd075d4a13435bb38d36d36d355e2c":{
        "scriptId":"u41"},
      "bb403b174c84493fb4f494d656fe76be":{
        "scriptId":"u42"},
      "58960e18088740d6b430de5d372859ea":{
        "scriptId":"u43"},
      "55ded9c022034980874697e6ecf96b50":{
        "scriptId":"u44"},
      "10fd560854464e449efe80171de9a593":{
        "scriptId":"u45"}},
    "0ff3758664d049479ba92e842dc941f8":{
      "scriptId":"u46"},
    "6b6fcaae23c147a58451f009b7508bc1":{
      "scriptId":"u47"},
    "d471220ab112430f8d1098c9ac7867e2":{
      "scriptId":"u48"},
    "2bdd23492b5544ffb2b6fc50f22ff163":{
      "scriptId":"u49"},
    "eac4ff449d744f6695ed12c489301c16":{
      "scriptId":"u50"},
    "7a5800f74a6348909d0728627d13f823":{
      "scriptId":"u51"},
    "c2811a26fee5459685b96a3a3f740ce5":{
      "scriptId":"u52"},
    "73a62805a8464e19b1f073793535c1e8":{
      "scriptId":"u53"},
    "969bfdf7fa6240c99aa8599b277f1e9d":{
      "scriptId":"u54"},
    "f132b057c7aa4a83bc9a8bf3427a5fe2":{
      "scriptId":"u55"},
    "9b66a90ba2cb4e90bd3bb596ffce3ca2":{
      "scriptId":"u56"},
    "14f9438f679b449ab532922bdc399ef9":{
      "scriptId":"u57"},
    "89ddc17f05b644408b5eb507822aead1":{
      "scriptId":"u58"},
    "3aaecd971a3241b1b55943e2cfe93e12":{
      "scriptId":"u59"},
    "1922ff205e824d679cd58baece15a01c":{
      "scriptId":"u60"},
    "7b48cbf77e01412d802a6eca3399c147":{
      "scriptId":"u61"},
    "9ad651fee56e42d6954a28aee57f9984":{
      "scriptId":"u62"},
    "a75cd3fd6d8b431dad1375234148062e":{
      "scriptId":"u63"},
    "7e1e40c9dccb4c119364ecdeb2d7aeac":{
      "scriptId":"u64"},
    "ac784b189d6f4306b40f95bd62b6b25b":{
      "scriptId":"u65"},
    "39760a805a304dbdb305b9d8333a46f1":{
      "scriptId":"u66"},
    "3179d4fd50ed494d92d53b35a8b78560":{
      "scriptId":"u67"},
    "d1174c9a5c4c4c16858ef53118c9514c":{
      "scriptId":"u68"},
    "416557cd87664b61a647f99c3c57a079":{
      "scriptId":"u69"},
    "926673b9f9884c5f8980dc3c0bef61e8":{
      "scriptId":"u70"},
    "14e569bc842f43fb968baeadca3b4803":{
      "scriptId":"u71"},
    "395032646ad5440a9e43bbc8234f36b7":{
      "scriptId":"u72"},
    "69176f5d8cc94fa7b2086f93e3c78933":{
      "scriptId":"u73"},
    "2195891900a14663ae54f25dfd50e456":{
      "scriptId":"u74"},
    "cfc81a13aa6e4fc6b54e066711966a80":{
      "scriptId":"u75"},
    "8c5441a42fe246d5a1f9690fe52ad882":{
      "scriptId":"u76"},
    "20582ec4a7674a5392fbc9df713f09f8":{
      "scriptId":"u77"},
    "1531a8536a04423e963b25c19ca5f35b":{
      "scriptId":"u78"},
    "7baef41763744286a21fa748a0b361ca":{
      "scriptId":"u79"},
    "0b074067f4a64a2dadd7ea103c2908ee":{
      "scriptId":"u80"},
    "6075a987cf334f2dac43c4eb95c11419":{
      "scriptId":"u81"},
    "191ed4e431bf4a948c11bcfcf5d84af4":{
      "scriptId":"u82"},
    "bb4250507fdc41e792d9805e5d2bbed6":{
      "scriptId":"u83"},
    "479c4343e44c40c5bf5ad8968908b209":{
      "scriptId":"u84"},
    "876e009aab3a45128136c30b11135d91":{
      "scriptId":"u85"},
    "e4a73eef52234ff49f99e1b203b679b5":{
      "scriptId":"u86"},
    "42aa3abadac746b08a6908fd12527b20":{
      "scriptId":"u87"},
    "14aaa6380dc742db855b722caa0f5919":{
      "scriptId":"u88"}}});