$axure.loadCurrentPage({
  "url":"brukervilk_r.html",
  "generationDate":new Date(1398865214783.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"13c7b6fca4fe499a86cf67f544c086b5",
    "type":"Axure:Page",
    "name":"brukervilkår",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF2F2F2},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f6570c2fa9974261a8884ea384550060",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":160},
            "size":{
              "width":980,
              "height":650},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80e9a89c6fc7462fb6dfbf1c4f4db830",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":160},
                "size":{
                  "width":980,
                  "height":650},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/om_aid/u0.png"}},
{
          "id":"1a8f02526bcb46eaa98464bbd13a0282",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-3,
              "y":-5},
            "size":{
              "width":1053,
              "height":92}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d5ce9175e92413ca78b11a543c1e035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-3,
                  "y":-5},
                "size":{
                  "width":1053,
                  "height":92}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/oversikt/u4.jpg"}},
{
          "id":"f59461b2a088496b8057b17f64f05d17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
            "fontSize":"24px",
            "location":{
              "x":58,
              "y":291},
            "size":{
              "width":978,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f5d0b1eb36b41fb8a33d491069fc615",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                "fontSize":"24px",
                "location":{
                  "x":58,
                  "y":291},
                "size":{
                  "width":978,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6d14c6d98844a1998ab89d00ad156d7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":330},
            "size":{
              "width":920,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEEEEEE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/oversikt/u20_line.png"}},
{
          "id":"3f569d7bac5843929e1eea52414feaaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "location":{
              "x":60,
              "y":360},
            "size":{
              "width":920,
              "height":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e36d9c114940e0b487a6af1959a2a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "location":{
                  "x":60,
                  "y":360},
                "size":{
                  "width":920,
                  "height":440}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1894d2ed61bc43d886c1ec6f5556ec57",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":840}},
          "adaptiveStyles":{
},
          "masterId":"c659a0f679d04fa3be4f0c9bb83a92a5"},
{
          "id":"75cb2f79e1784eadb396f280ec5e390c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":160}},
          "adaptiveStyles":{
},
          "masterId":"69ae6806ee54475b974f31d4bce44331"}]}},
  "masters":{
    "c659a0f679d04fa3be4f0c9bb83a92a5":{
      "packageId":"c659a0f679d04fa3be4f0c9bb83a92a5",
      "type":"Axure:Master",
      "name":"footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa0ca7c8a63c4fd698183d08b0ff05e4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF434343},
              "size":{
                "width":1130,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"284f9be7fc4a433fb44b893ec408a26a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF434343},
                  "size":{
                    "width":1130,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/oversikt/u31.png"}},
{
            "id":"2fc7f94f44854415ab9e3c40eb4dcde6",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"40px",
              "location":{
                "x":30,
                "y":38},
              "size":{
                "width":65,
                "height":49}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a841b7cca0145c7affcdf3c4d3398fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"40px",
                  "location":{
                    "x":30,
                    "y":38},
                  "size":{
                    "width":65,
                    "height":49}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"32ed36c9cdc142c58eb9a13f6aac752b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"19px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":130,
                "y":54},
              "size":{
                "width":890,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78b58fd08b6f4c858cc0fde0d1540747",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"19px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":130,
                    "y":54},
                  "size":{
                    "width":890,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c6c65c43030740ab9cb8c0e1d082d1a1",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":117,
                "y":43},
              "size":{
                "width":90,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open om aid in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"om_aid.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"57806af78fc74ed59ed355709d584671",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":43},
              "size":{
                "width":130,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open brukervilkår in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"brukervilk_r.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "69ae6806ee54475b974f31d4bce44331":{
      "packageId":"69ae6806ee54475b974f31d4bce44331",
      "type":"Axure:Master",
      "name":"header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c310211d63d941b7a63709b51e13d0d2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF605857},
              "size":{
                "width":980,
                "height":80},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b0dd075d4a13435bb38d36d36d355e2c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF605857},
                  "size":{
                    "width":980,
                    "height":80},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/oversikt/u40.png"}},
{
            "id":"bb403b174c84493fb4f494d656fe76be",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
              "fontSize":"34px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":150,
                "y":21},
              "size":{
                "width":580,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58960e18088740d6b430de5d372859ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                  "fontSize":"34px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":150,
                    "y":21},
                  "size":{
                    "width":580,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"55ded9c022034980874697e6ecf96b50",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'HelveticaNeue', 'Helvetica Neue'",
              "fontSize":"55px",
              "location":{
                "x":29,
                "y":7},
              "size":{
                "width":90,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"10fd560854464e449efe80171de9a593",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'HelveticaNeue', 'Helvetica Neue'",
                  "fontSize":"55px",
                  "location":{
                    "x":29,
                    "y":7},
                  "size":{
                    "width":90,
                    "height":68}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open oversikt in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"oversikt.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "f6570c2fa9974261a8884ea384550060":{
      "scriptId":"u0"},
    "80e9a89c6fc7462fb6dfbf1c4f4db830":{
      "scriptId":"u1"},
    "1a8f02526bcb46eaa98464bbd13a0282":{
      "scriptId":"u2"},
    "5d5ce9175e92413ca78b11a543c1e035":{
      "scriptId":"u3"},
    "f59461b2a088496b8057b17f64f05d17":{
      "scriptId":"u4"},
    "5f5d0b1eb36b41fb8a33d491069fc615":{
      "scriptId":"u5"},
    "a6d14c6d98844a1998ab89d00ad156d7":{
      "scriptId":"u6"},
    "3f569d7bac5843929e1eea52414feaaf":{
      "scriptId":"u7"},
    "e1e36d9c114940e0b487a6af1959a2a1":{
      "scriptId":"u8"},
    "1894d2ed61bc43d886c1ec6f5556ec57":{
      "scriptId":"u9",
      "aa0ca7c8a63c4fd698183d08b0ff05e4":{
        "scriptId":"u10"},
      "284f9be7fc4a433fb44b893ec408a26a":{
        "scriptId":"u11"},
      "2fc7f94f44854415ab9e3c40eb4dcde6":{
        "scriptId":"u12"},
      "5a841b7cca0145c7affcdf3c4d3398fa":{
        "scriptId":"u13"},
      "32ed36c9cdc142c58eb9a13f6aac752b":{
        "scriptId":"u14"},
      "78b58fd08b6f4c858cc0fde0d1540747":{
        "scriptId":"u15"},
      "c6c65c43030740ab9cb8c0e1d082d1a1":{
        "scriptId":"u16"},
      "57806af78fc74ed59ed355709d584671":{
        "scriptId":"u17"}},
    "75cb2f79e1784eadb396f280ec5e390c":{
      "scriptId":"u18",
      "c310211d63d941b7a63709b51e13d0d2":{
        "scriptId":"u19"},
      "b0dd075d4a13435bb38d36d36d355e2c":{
        "scriptId":"u20"},
      "bb403b174c84493fb4f494d656fe76be":{
        "scriptId":"u21"},
      "58960e18088740d6b430de5d372859ea":{
        "scriptId":"u22"},
      "55ded9c022034980874697e6ecf96b50":{
        "scriptId":"u23"},
      "10fd560854464e449efe80171de9a593":{
        "scriptId":"u24"}}}});