$axure.loadCurrentPage({
  "url":"insentivside_5.html",
  "generationDate":new Date(1398346613125.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"79d205efc92e45daae714e047202c086",
    "type":"Axure:Page",
    "name":"insentivside",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9485d31d5a0c434ea28c51dcd1c47bcf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":600},
            "size":{
              "width":750,
              "height":502}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee9f4bc7d9a14bffbb41bbaa7c8021e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":600},
                "size":{
                  "width":750,
                  "height":502}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u0.jpg"}},
{
          "id":"f2f90857189f4fd4982fb6b3f115573c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":270},
            "size":{
              "width":750,
              "height":330},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91f72c0612a64675a4e6f6a4e3918033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":270},
                "size":{
                  "width":750,
                  "height":330},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u2.png"}},
{
          "id":"afe9564566324d818afd3ed33c60eb6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontWeight":"900",
            "horizontalAlignment":"center",
            "location":{
              "x":10,
              "y":300},
            "size":{
              "width":740,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61533205a7f64b17add8f450c5f3c0b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontWeight":"900",
                "horizontalAlignment":"center",
                "location":{
                  "x":10,
                  "y":300},
                "size":{
                  "width":740,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cb27d5968f54125a665c6147092d0ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":750,
              "height":222}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88adc781762340e6ba6f98026e8948b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":750,
                  "height":222}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u6.jpg"}},
{
          "id":"e95cd1ca91a84b9a8a61440b2f707989",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":595},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/insentivside/u8_line.png"}},
{
          "id":"30281ac403d44a47bb926b3c97857ba7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":240,
              "y":370},
            "size":{
              "width":280,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b7e5659279a475ab54feb9318bcf75e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":240,
                  "y":370},
                "size":{
                  "width":280,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u9.png"}},
{
          "id":"b1368ffcfe37498b88c2acf1267972f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":30,
              "y":440},
            "size":{
              "width":340,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4134618a046444d8aad218377425728",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":30,
                  "y":440},
                "size":{
                  "width":340,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u11.png"}},
{
          "id":"ad935088dfdf4df6bdcb4e19d4261afa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":390,
              "y":440},
            "size":{
              "width":340,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb36ce9b0344a1e9cc1e19a2d807f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":390,
                  "y":440},
                "size":{
                  "width":340,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u11.png"}},
{
          "id":"f02e708eb76d4416b3c3d75c76d1b0ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "lineSpacing":"20px",
            "location":{
              "x":30,
              "y":490},
            "size":{
              "width":340,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc5dd008d6be434bb1e0e40c7407e33b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "lineSpacing":"20px",
                "location":{
                  "x":30,
                  "y":490},
                "size":{
                  "width":340,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a820fdd20ba74ce2ab13c5fddf0eb487",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "lineSpacing":"20px",
            "location":{
              "x":390,
              "y":490},
            "size":{
              "width":340,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4486d88525d049c58d127b48c09198f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "lineSpacing":"20px",
                "location":{
                  "x":390,
                  "y":490},
                "size":{
                  "width":340,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da49e325fa284c77ab15bed88c875c15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontSize":"34px",
            "fontWeight":"900",
            "location":{
              "x":130,
              "y":604},
            "size":{
              "width":490,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaa1598247e84dec8ccee442a09ac78c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontSize":"34px",
                "fontWeight":"900",
                "location":{
                  "x":130,
                  "y":604},
                "size":{
                  "width":490,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u19.png"}},
{
          "id":"6c9e540ab4fa4eddb3a4bc4797d33429",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":98,
              "y":687},
            "size":{
              "width":82,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c31625d7c13643de908a65c01c6e5ff9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":98,
                  "y":687},
                "size":{
                  "width":82,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u21.png"}},
{
          "id":"605dbb956f724c90a0140672ea59a81c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":960},
            "size":{
              "width":290,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open tilgang/login in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"tilgang_login_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "9485d31d5a0c434ea28c51dcd1c47bcf":{
      "scriptId":"u0"},
    "ee9f4bc7d9a14bffbb41bbaa7c8021e1":{
      "scriptId":"u1"},
    "f2f90857189f4fd4982fb6b3f115573c":{
      "scriptId":"u2"},
    "91f72c0612a64675a4e6f6a4e3918033":{
      "scriptId":"u3"},
    "afe9564566324d818afd3ed33c60eb6d":{
      "scriptId":"u4"},
    "61533205a7f64b17add8f450c5f3c0b9":{
      "scriptId":"u5"},
    "6cb27d5968f54125a665c6147092d0ce":{
      "scriptId":"u6"},
    "88adc781762340e6ba6f98026e8948b5":{
      "scriptId":"u7"},
    "e95cd1ca91a84b9a8a61440b2f707989":{
      "scriptId":"u8"},
    "30281ac403d44a47bb926b3c97857ba7":{
      "scriptId":"u9"},
    "2b7e5659279a475ab54feb9318bcf75e":{
      "scriptId":"u10"},
    "b1368ffcfe37498b88c2acf1267972f6":{
      "scriptId":"u11"},
    "f4134618a046444d8aad218377425728":{
      "scriptId":"u12"},
    "ad935088dfdf4df6bdcb4e19d4261afa":{
      "scriptId":"u13"},
    "bbb36ce9b0344a1e9cc1e19a2d807f3a":{
      "scriptId":"u14"},
    "f02e708eb76d4416b3c3d75c76d1b0ab":{
      "scriptId":"u15"},
    "dc5dd008d6be434bb1e0e40c7407e33b":{
      "scriptId":"u16"},
    "a820fdd20ba74ce2ab13c5fddf0eb487":{
      "scriptId":"u17"},
    "4486d88525d049c58d127b48c09198f1":{
      "scriptId":"u18"},
    "da49e325fa284c77ab15bed88c875c15":{
      "scriptId":"u19"},
    "eaa1598247e84dec8ccee442a09ac78c":{
      "scriptId":"u20"},
    "6c9e540ab4fa4eddb3a4bc4797d33429":{
      "scriptId":"u21"},
    "c31625d7c13643de908a65c01c6e5ff9":{
      "scriptId":"u22"},
    "605dbb956f724c90a0140672ea59a81c":{
      "scriptId":"u23"}}});