$axure.loadCurrentPage({
  "url":"tast_engangskode_2.html",
  "generationDate":new Date(1400834763680.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"03a8e1414b044780978be8d5766465cf",
    "type":"Axure:Page",
    "name":"tast engangskode",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b66713c9cb746faaea7152a3f199e3b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2b40fb19f33c450284c7533e94ceefb7"},
{
          "id":"5ddb37003fbd4622b3080b079976d9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":150},
            "size":{
              "width":580,
              "height":190},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22209f2983394fe0a1ac365e72dcab40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":150},
                "size":{
                  "width":580,
                  "height":190},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tast_engangskode/u3.png"}},
{
          "id":"8b1c9cc57d4948ce85e084b1a9e31521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
            "fontSize":"34px",
            "fontWeight":"900",
            "location":{
              "x":120,
              "y":150},
            "size":{
              "width":490,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169bee24748c4e5eb8343ae57d6ce259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'GuardianSansWeb-Black', 'Guardian Sans Web Black'",
                "fontSize":"34px",
                "fontWeight":"900",
                "location":{
                  "x":120,
                  "y":150},
                "size":{
                  "width":490,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tilgang_login_-_responsive_view/u5.png"}},
{
          "id":"ce841c68e270422fbe05b834ba782bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":432,
              "y":279},
            "size":{
              "width":115,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8325cc45365d44979604392a79c124d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":432,
                  "y":279},
                "size":{
                  "width":115,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tast_engangskode/u7.png"}},
{
          "id":"c512aaf2c7674daf9029f8ec3ed9c489",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "paddingTop":"20",
            "paddingBottom":"20",
            "location":{
              "x":100,
              "y":210},
            "size":{
              "width":540,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e24ae10884a48d19297211bec8059b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "paddingTop":"20",
                "paddingBottom":"20",
                "location":{
                  "x":100,
                  "y":210},
                "size":{
                  "width":540,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bfaba4595104a149fa9870eae30b24d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":182,
              "y":279},
            "size":{
              "width":240,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"439ccad09662470d8d5abf2c1deb0caa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":182,
                  "y":279},
                "size":{
                  "width":240,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tilgang_login_-_responsive_view/u11.png"}},
{
          "id":"c864f21e72d5405ea1b90e8c8170de17",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":270},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open velg passord in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"velg_passord_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "2b40fb19f33c450284c7533e94ceefb7":{
      "packageId":"2b40fb19f33c450284c7533e94ceefb7",
      "type":"Axure:Master",
      "name":"newspaper-header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f116adf1346348c589d6534e6e84206f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":753,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16de1730a3c245c88590db8c75a43f16",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":753,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/tilgang_login_-_responsive_view/u1.jpg"}}]}}},
  "objectPaths":{
    "3b66713c9cb746faaea7152a3f199e3b":{
      "scriptId":"u0",
      "f116adf1346348c589d6534e6e84206f":{
        "scriptId":"u1"},
      "16de1730a3c245c88590db8c75a43f16":{
        "scriptId":"u2"}},
    "5ddb37003fbd4622b3080b079976d9d0":{
      "scriptId":"u3"},
    "22209f2983394fe0a1ac365e72dcab40":{
      "scriptId":"u4"},
    "8b1c9cc57d4948ce85e084b1a9e31521":{
      "scriptId":"u5"},
    "169bee24748c4e5eb8343ae57d6ce259":{
      "scriptId":"u6"},
    "ce841c68e270422fbe05b834ba782bd4":{
      "scriptId":"u7"},
    "8325cc45365d44979604392a79c124d2":{
      "scriptId":"u8"},
    "c512aaf2c7674daf9029f8ec3ed9c489":{
      "scriptId":"u9"},
    "9e24ae10884a48d19297211bec8059b2":{
      "scriptId":"u10"},
    "9bfaba4595104a149fa9870eae30b24d":{
      "scriptId":"u11"},
    "439ccad09662470d8d5abf2c1deb0caa":{
      "scriptId":"u12"},
    "c864f21e72d5405ea1b90e8c8170de17":{
      "scriptId":"u13"}}});