$axure.loadCurrentPage({
  "url":"opprett_bruker_5.html",
  "generationDate":new Date(1398346613920.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"14df113872fe4e1e8f341514ad61b5ac",
    "type":"Axure:Page",
    "name":"opprett bruker",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b66713c9cb746faaea7152a3f199e3b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2b40fb19f33c450284c7533e94ceefb7"},
{
          "id":"5ddb37003fbd4622b3080b079976d9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":150},
            "size":{
              "width":580,
              "height":430},
            "borderWidth":"-1",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22209f2983394fe0a1ac365e72dcab40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":150},
                "size":{
                  "width":580,
                  "height":430},
                "borderWidth":"-1",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u3.png"}},
{
          "id":"8b1c9cc57d4948ce85e084b1a9e31521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":120,
              "y":150},
            "size":{
              "width":490,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169bee24748c4e5eb8343ae57d6ce259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":120,
                  "y":150},
                "size":{
                  "width":490,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/insentivside/u19.png"}},
{
          "id":"db3c968df9b9485e87b4bb0480dcde3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":245,
              "y":260},
            "size":{
              "width":240,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3cd2c0ef1e548a4b95145ca4c666e15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":245,
                  "y":260},
                "size":{
                  "width":240,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tilgang_login/u11.png"}},
{
          "id":"ce841c68e270422fbe05b834ba782bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
            "fontSize":"19px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":245,
              "y":520},
            "size":{
              "width":240,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8325cc45365d44979604392a79c124d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-CondensedBold', 'Open Sans Condensed Bold', 'Open Sans Condensed'",
                "fontSize":"19px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":245,
                  "y":520},
                "size":{
                  "width":240,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker_1/u9.png"}},
{
          "id":"979dfbbe5cef4883b61f433fb81f9536",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":246,
              "y":241},
            "size":{
              "width":239,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b13397d8283d4af0beb05ec07c562d57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":246,
                  "y":241},
                "size":{
                  "width":239,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"087b3967c0404913a62fc8d11ba7f23b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":245,
              "y":339},
            "size":{
              "width":240,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"862aba929ca34bff8b9d5f071011f626",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":245,
                  "y":339},
                "size":{
                  "width":240,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tilgang_login/u11.png"}},
{
          "id":"79881308ca534806a631a3f0f30b179a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":246,
              "y":320},
            "size":{
              "width":239,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a4c7094831e408baa5e1ae7bd7648c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":246,
                  "y":320},
                "size":{
                  "width":239,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"954c0c7f24f2416aa021dd97d22d2ed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":245,
              "y":419},
            "size":{
              "width":240,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09dc779c5bb74aa1a139915f7a55e1db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":245,
                  "y":419},
                "size":{
                  "width":240,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tilgang_login/u11.png"}},
{
          "id":"64da8295c22a48e0a7111fa8aa3265b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":246,
              "y":400},
            "size":{
              "width":239,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b568bafc39e14399b719a10febd36b6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":246,
                  "y":400},
                "size":{
                  "width":239,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faacc81019de4138bcbe306ca7639459",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":245,
              "y":480},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67b1453fd6b49518c472220275fa18a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":245,
                  "y":480},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/opprett_bruker/u21.png"}},
{
          "id":"4febbe64660f4418b184f725ae5fada6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":272,
              "y":482},
            "size":{
              "width":239,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16c08e12bf0c4fd1be8588781a4e39e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":272,
                  "y":482},
                "size":{
                  "width":239,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2b40fb19f33c450284c7533e94ceefb7":{
      "packageId":"2b40fb19f33c450284c7533e94ceefb7",
      "type":"Axure:Master",
      "name":"newspaper-header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f116adf1346348c589d6534e6e84206f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-1},
              "size":{
                "width":753,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16de1730a3c245c88590db8c75a43f16",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-1},
                  "size":{
                    "width":753,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/tilgang_login/u1.jpg"}}]}}},
  "objectPaths":{
    "3b66713c9cb746faaea7152a3f199e3b":{
      "scriptId":"u0",
      "f116adf1346348c589d6534e6e84206f":{
        "scriptId":"u1"},
      "16de1730a3c245c88590db8c75a43f16":{
        "scriptId":"u2"}},
    "5ddb37003fbd4622b3080b079976d9d0":{
      "scriptId":"u3"},
    "22209f2983394fe0a1ac365e72dcab40":{
      "scriptId":"u4"},
    "8b1c9cc57d4948ce85e084b1a9e31521":{
      "scriptId":"u5"},
    "169bee24748c4e5eb8343ae57d6ce259":{
      "scriptId":"u6"},
    "db3c968df9b9485e87b4bb0480dcde3c":{
      "scriptId":"u7"},
    "d3cd2c0ef1e548a4b95145ca4c666e15":{
      "scriptId":"u8"},
    "ce841c68e270422fbe05b834ba782bd4":{
      "scriptId":"u9"},
    "8325cc45365d44979604392a79c124d2":{
      "scriptId":"u10"},
    "979dfbbe5cef4883b61f433fb81f9536":{
      "scriptId":"u11"},
    "b13397d8283d4af0beb05ec07c562d57":{
      "scriptId":"u12"},
    "087b3967c0404913a62fc8d11ba7f23b":{
      "scriptId":"u13"},
    "862aba929ca34bff8b9d5f071011f626":{
      "scriptId":"u14"},
    "79881308ca534806a631a3f0f30b179a":{
      "scriptId":"u15"},
    "3a4c7094831e408baa5e1ae7bd7648c8":{
      "scriptId":"u16"},
    "954c0c7f24f2416aa021dd97d22d2ed8":{
      "scriptId":"u17"},
    "09dc779c5bb74aa1a139915f7a55e1db":{
      "scriptId":"u18"},
    "64da8295c22a48e0a7111fa8aa3265b7":{
      "scriptId":"u19"},
    "b568bafc39e14399b719a10febd36b6c":{
      "scriptId":"u20"},
    "faacc81019de4138bcbe306ca7639459":{
      "scriptId":"u21"},
    "e67b1453fd6b49518c472220275fa18a":{
      "scriptId":"u22"},
    "4febbe64660f4418b184f725ae5fada6":{
      "scriptId":"u23"},
    "16c08e12bf0c4fd1be8588781a4e39e6":{
      "scriptId":"u24"}}});